import assert from 'node:assert/strict';
import * as C from '../src/core.js';

const now=1700000000000;
let s=C.createSave(now);
assert.equal(s.version,5);
assert.ok(Number.isFinite(s.timeAnchor),'new saves keep a persistent island clock');
let morning=C.battlePeriodAt(0,0),noon=C.battlePeriodAt(0,C.BATTLE_PERIOD_MS),afternoon=C.battlePeriodAt(0,C.BATTLE_PERIOD_MS*2),night=C.battlePeriodAt(0,C.BATTLE_PERIOD_MS*3);assert.deepEqual([morning.id,noon.id,afternoon.id,night.id],['morning','noon','afternoon','night']);assert.equal(C.BATTLE_PERIOD_MS,180000);assert.equal(C.BATTLE_DAY_MS,720000,'the full seamless day/night loop lasts 12 minutes');assert.equal(C.battlePeriodAt(0,C.BATTLE_DAY_MS).id,'morning','the compressed day loops without a discontinuity');assert.equal(C.battlePeriodAt(C.battleTimeAnchor(17,now),now+C.BATTLE_PERIOD_MS).index,(C.battlePeriodAt(C.battleTimeAnchor(17,now),now).index+1)%4,'a scouted clock advances one period every three minutes');
for(const [minutes,id,clock] of [[8*60,'morning','08:00'],[13*60,'noon','13:00'],[17*60,'afternoon','17:00'],[22*60,'night','22:00'],[2*60,'night','02:00']]){let set=C.battlePeriodAt(C.battleTimeAnchorAtClock(minutes,now),now);assert.equal(set.id,id,'base clock preset selects the expected environment');assert.equal(set.clock,clock,'base clock preset preserves the requested wall clock')}
assert.deepEqual(s.base.map(b=>b.type),['hq'],'start with HQ only');
assert.equal(C.boatCapacity(s)*s.craft.count,C.capacity(s));
assert.deepEqual(C.boatManifest(s).map(b=>[b.type,b.count]),[['rifle',8],['heavy',2],['rocket',2]]);
assert.equal(C.UNLOCK.tank,2);assert.equal(C.UNLOCK.medic,2);
assert.equal(C.UNLOCK.rocket,1,'rocket troop is available from HQ 1');
assert.equal(C.BUILD_UNLOCK.rocket,5,'rocket launcher is built at HQ 5');
assert.equal(C.BUILD_UNLOCK.missile,6,'anti-tank missile launcher is built at HQ 6');
let gunboat=C.createSave(now),firstEnergy=C.boatEnergy(gunboat.gunboat.level),firstGold=gunboat.resources.gold;
assert.match(C.upgradeGunboat(gunboat,now),/司令部 Lv.2/,'HQ1 must not own an over-level gunboat');
gunboat.base[0].lvl=2;assert.match(C.upgradeGunboat(gunboat,now),/战舰 Lv.2/,'HQ2 can queue the matching gunboat level');
assert.equal(gunboat.resources.gold,firstGold-C.gunboatUpgradeCost(2)[0]);
assert.equal(C.boatEnergy(gunboat.gunboat.level),firstEnergy,'queued upgrade does not finish instantly');
assert.match(C.upgradeGunboat(gunboat,now),/建造\/升级位忙碌/);
C.settle(gunboat,now+40000,false);assert.equal(C.boatEnergy(gunboat.gunboat.level),firstEnergy+3);
assert.match(C.upgradeGunboat(gunboat,now+40001),/司令部 Lv.3 解锁/);
gunboat.base[0].lvl=3;assert.match(C.upgradeGunboat(gunboat,now+40001),/战舰 Lv.3/);
let craftShop=C.createSave(now);craftShop.base[0].lvl=3;let newCraftPrice=C.craftBuildCost(craftShop),craftShopBefore=C.clone(craftShop.resources);assert.deepEqual(newCraftPrice,[380,700,540]);assert.match(C.addCraft(craftShop,now),/第 4 艘登陆艇建造中/);assert.equal(craftShop.craft.count,3);assert.match(C.addCraft(craftShop,now),/建造\/升级位忙碌/);C.settle(craftShop,now+48000,false);assert.equal(craftShop.craft.count,4);assert.deepEqual(C.RES.map((key,i)=>craftShopBefore[key]-craftShop.resources[key]),newCraftPrice,'shop construction charges the displayed landing-craft price');
let weaponState=C.createSave(now);assert.match(C.upgradeWeapon(weaponState,'barrage',now),/先升级司令部/);weaponState.base[0].lvl=2;assert.match(C.upgradeWeapon(weaponState,'barrage',now),/先升级战舰/);C.upgradeGunboat(weaponState,now);C.settle(weaponState,now+40000,false);let weaponAt=now+40001,weaponQuote=C.weaponUpgradeCost('barrage',1),beforeWeapon=C.clone(weaponState.resources);assert.deepEqual(weaponQuote.slice(1),[0,0],'weapon training only costs gold');assert.match(C.upgradeWeapon(weaponState,'barrage',weaponAt),/训练升级中/);assert.equal(weaponState.training[0].weapon,'barrage');assert.deepEqual(C.RES.map((key,i)=>beforeWeapon[key]-weaponState.resources[key]),weaponQuote);assert.match(C.upgradeWeapon(weaponState,'barrage',weaponAt),/训练位忙碌/);let weaponSaved=C.loadSave({getItem:()=>JSON.stringify(weaponState)},weaponAt+1000);assert.equal(weaponSaved.gunboat.weaponLevels.barrage,1);C.settle(weaponSaved,weaponAt+C.weaponUpgradeSeconds(1)*1000,false);assert.equal(weaponSaved.gunboat.weaponLevels.barrage,2);let trained=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],12,'attack',null,2,C.MAP.spawnZ,7,weaponSaved.gunboat.weaponLevels);trained.useSkill('barrage',0,0);assert.equal(trained.gunboatShells[0].damage,73);assert.equal(trained.snapshot().weaponLevels.barrage,2);let trainedReplay=C.replayBattle(trained.snapshot());trainedReplay.battle.useSkill('barrage',0,0);assert.deepEqual(trainedReplay.battle.gunboatShells,trained.gunboatShells,'replay locks trained weapon level');
let tierLocked=C.createSave(now);tierLocked.base[0].lvl=6;tierLocked.gunboat.level=7;tierLocked.gunboat.weaponLevels.fire=5;tierLocked.resources.gold=99999;let tierAt=now+200000;assert.equal(C.weaponLevelCap(tierLocked),6,'HQ6 caps weapons at Lv.6 even when a legacy save owns a Lv.7 gunboat');assert.match(C.upgradeWeapon(tierLocked,'fire',tierAt),/训练升级中/,'HQ6 must allow its Lv.5 weapon to reach Lv.6');C.settle(tierLocked,tierAt+C.weaponUpgradeSeconds(5)*1000,false);assert.equal(tierLocked.gunboat.weaponLevels.fire,6);assert.match(C.upgradeWeapon(tierLocked,'fire',tierAt+C.weaponUpgradeSeconds(5)*1000+1),/先升级司令部/);assert.match(C.upgradeGunboat(tierLocked,tierAt),/已高于司令部/,'legacy over-level gunboat is preserved but cannot advance');let tierReload=C.loadSave({getItem:()=>JSON.stringify(tierLocked)},tierAt+C.weaponUpgradeSeconds(5)*1000+2);assert.equal(tierReload.gunboat.level,7,'existing paid over-level gunboat must not be downgraded');assert.equal(tierReload.gunboat.weaponLevels.fire,6,'loading a save must retain the legal HQ6 weapon level');let highWeaponBattle=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:7}],66,'attack',null,7,C.MAP.spawnZ,24,{fire:7,barrage:7,flare:7,medkit:7,shock:7});assert.equal(highWeaponBattle.weaponLevels.fire,7);highWeaponBattle.useSkill('fire',0,0);assert.equal(highWeaponBattle.gunboatShells[0].damage,213,'levels above five use diminishing weapon growth');assert.ok(C.weaponUpgradeCost('fire',6)[0]>C.weaponUpgradeCost('fire',5)[0]&&C.weaponUpgradeSeconds(6)>C.weaponUpgradeSeconds(5),'late weapon levels must get materially more expensive and slower');
let slots=C.createSave(now);slots.base[0].lvl=2;slots.base.push({id:2,type:'gold',x:-8,z:4,lvl:1,stored:0});assert.match(C.startUpgrade(slots,2,now),/升级中/);let peopleBefore=C.clone(slots.army);assert.match(C.upgradeUnit(slots,'rifle',now),/训练升级中/,'training and engineering slots run in parallel');assert.deepEqual(slots.army,peopleBefore,'training upgrades a type and never creates idle personnel');assert.equal(slots.training[0].unit,'rifle');let slotGold=slots.resources.gold;assert.match(C.upgradeUnit(slots,'heavy',now),/训练位忙碌/);assert.match(C.buildAt(slots,'wood',8,4,now),/当前升级完成/);assert.equal(slots.resources.gold,slotGold,'blocked second jobs spend nothing');let constructionSlot=C.createSave(now);constructionSlot.base[0].lvl=2;assert.match(C.buildAt(constructionSlot,'gold',-8,4,now),/开工/);assert.match(C.upgradeGunboat(constructionSlot,now),/建造\/升级位忙碌/);assert.match(C.upgradeUnit(constructionSlot,'rifle',now),/训练升级中/,'construction can run beside one training upgrade');
for(let level=1;level<=C.MAX_HQ_LEVEL;level++){let tier=C.HQ_TIERS[level],state=C.createSave(now);state.base[0].lvl=level;state.craft.levels.fill(level);assert.equal(C.maxBoats(state),tier.boats);assert.equal(C.boatCapacity(state,1),tier.boatCapacity);assert.deepEqual(C.HQ_BUILD_LIMITS[level],tier.build);assert.equal(tier.build.wood,1,'each HQ tier permits only one lumber mill');assert.equal(tier.build.steel,1,'each HQ tier permits only one steelworks');assert.equal(tier.build.vault,1,'every HQ tier permits exactly one vault');assert.equal(C.npcBuildCounts(level).vault,1,'NPCs use the same singleton vault quota');assert.ok(tier.npc[0]<=level&&tier.npc[1]>=level)}
let highCraft=C.createSave(now);highCraft.base[0].lvl=10;highCraft.craft.levels[0]=8;highCraft.craft.loadouts[0]='tank';highCraft.army.tank=4;assert.equal(C.boatCapacity(highCraft,0),20,'HQ8 landing craft must reach four-tank capacity');assert.equal(C.boatManifest(highCraft)[0].count,4,'four tanks must occupy one real HQ8 craft rather than a global capacity pool');highCraft.craft.levels[0]=10;assert.equal(C.boatCapacity(highCraft,0),22,'HQ10 craft stays at four tanks instead of jumping to five');let underCapacity=new C.Battle([{id:1,type:'hq',x:0,z:-6,lvl:1}],808);assert.equal(underCapacity.landBoat('tank',4,0,0,1,false,10.2,19),false,'a 19-slot craft cannot launch four tanks');assert.equal(underCapacity.landBoat('tank',4,0,0,1,false,10.2,20),true,'a 20-slot HQ8 craft can launch its four-tank load');
let highNpc=C.npcCommands([{id:1,type:'hq',x:0,z:-6,lvl:10}],810,10).commands.filter(c=>c.kind==='land');assert.ok(highNpc.length&&highNpc.every(c=>c.capacity===22),'HQ10 NPC landing commands must carry their real deck capacity');let highNpcBattle=new C.Battle([{id:1,type:'hq',x:0,z:-6,lvl:10}],810,'defense');for(let command of highNpc)assert.equal(highNpcBattle.landBoat(command.type,command.count,command.x,command.index,command.level,false,C.MAP.spawnZ,command.capacity),true,'high-level NPC craft load must fit its declared deck');
assert.equal(C.MAX_HQ_LEVEL,10);assert.equal(C.HQ_TIERS.length,C.MAX_HQ_LEVEL+1);assert.deepEqual(C.HQ_TIERS.map(t=>t?.npc??null),[null,[1,2],[1,3],[2,4],[3,5],[4,6],[5,7],[6,8],[7,9],[8,10],[9,10]],'matchmaking stays within one HQ level');
function progressionState(level,buildingLevel,trainingLevel=buildingLevel){let state=C.createSave(now);state.base[0].lvl=level;state.resources={gold:99999,wood:99999,steel:99999};let id=2;for(let [type,count] of Object.entries(C.HQ_BUILD_LIMITS[level]))if(type!=='store')for(let i=0;i<count;i++)state.base.push({id:id++,type,x:0,z:0,lvl:buildingLevel,...(C.RES.includes(type)?{stored:0}:{})});for(let type of Object.keys(C.UNIT))if(C.UNLOCK[type]<=level)state.unitLevels[type]=trainingLevel;state.gunboat.level=Math.max(state.gunboat.level,trainingLevel);for(let kind of Object.keys(C.SKILLS))state.gunboat.weaponLevels[kind]=trainingLevel;return state}
let sixReady=progressionState(6,4),sixStatus=C.hqUpgradeStatus(sixReady);assert.equal(sixStatus.minimumAverage,4,'HQ6 uses the rounded-up 60% threshold');assert.equal(sixStatus.average,4);assert.equal(sixStatus.ready,true);assert.match(C.startUpgrade(sixReady,1,now),/司令部升级中/,'a complete HQ6 base with 4.0 average may advance');
let sixLow=progressionState(6,3);assert.equal(C.hqUpgradeStatus(sixLow).ready,false);assert.match(C.startUpgrade(sixLow,1,now),/平均 3\.0 \/ 4\.0/,'HQ6 cannot advance below average level 4');
let sixMissing=progressionState(6,6,6);sixMissing.base.splice(sixMissing.base.findIndex(b=>b.type==='sniper'),1);assert.equal(C.hqUpgradeStatus(sixMissing).allBuilt,false);assert.match(C.startUpgrade(sixMissing,1,now),/先建完 狙击塔×1/,'high levels cannot compensate for a missing required building');
let compensated=progressionState(3,2);compensated.base.find(b=>b.type==='sniper').lvl=1;compensated.base.find(b=>b.type==='gold').lvl=3;let compensatedStatus=C.hqUpgradeStatus(compensated);assert.equal(compensatedStatus.minimumAverage,2);assert.equal(compensatedStatus.average,2);assert.equal(compensatedStatus.ready,true,'one low building may be balanced by another upgraded building');
let perBoat=C.createSave(now);perBoat.base[0].lvl=2;let craftPrice=C.craftUpgradeCost(perBoat,0),craftGold=perBoat.resources.gold;assert.match(C.upgradeCraft(perBoat,0,now),/1 号登陆艇升级中/);assert.deepEqual(perBoat.craft.levels,[1,1,1]);C.settle(perBoat,now+28000,false);assert.deepEqual(perBoat.craft.levels,[2,1,1]);assert.deepEqual([0,1,2].map(i=>C.boatCapacity(perBoat,i)),[10,8,8]);assert.equal(C.capacity(perBoat),26);assert.equal(perBoat.resources.gold,craftGold-craftPrice[0]);
let older=C.createSave(now);older.version=4;older.craft.level=3;delete older.craft.levels;let migrated=C.loadSave({getItem:()=>JSON.stringify(older)},now);assert.equal(migrated.version,5);assert.deepEqual(migrated.craft.levels,[3,3,3],'existing all-craft upgrade remains on each craft');assert.equal(C.capacity(migrated),36);
let legacyIdle=C.createSave(now);legacyIdle.army.rifle=10;legacyIdle.training=[{type:'rifle',start:now,end:now+10000}];let legacyGold=legacyIdle.resources.gold,cleaned=C.loadSave({getItem:()=>JSON.stringify(legacyIdle)},now+1);assert.equal(cleaned.army.rifle,8);assert.equal(cleaned.training.length,0);assert.equal(cleaned.resources.gold,legacyGold+3*C.trainingCost('rifle'));assert.match(cleaned.migrationNotice,/取消闲置人员/);
assert.match(C.upgradeUnit(s,'medic',now),/司令部 2 级解锁/);
assert.equal(C.setBoatLoadout(s,0,'medic').ok,false);
let refitPrice=C.boatRefitQuote(s,0,'heavy');assert.equal(refitPrice.count,4);assert.equal(refitPrice.difference,4*C.trainingCost('heavy')-8*C.trainingCost('rifle'));
assert.equal(C.setBoatLoadout(s,0,'heavy',now).ok,true);assert.equal(s.resources.gold,1500-refitPrice.difference);
assert.deepEqual(C.boatManifest(s).map(b=>b.count),[0,2,2],'refitting boat cannot sortie or steal another boat’s troops');
assert.equal(C.setBoatLoadout(s,0,'rifle',now).ok,false,'no free instant reversal');
C.settle(s,now+refitPrice.seconds*1000,false);assert.deepEqual(C.boatManifest(s).map(b=>b.count),[4,2,2],'new crew arrives after wait');
assert.equal(C.setBoatLoadout(s,0,'rifle',now+25000).ok,true);assert.equal(s.resources.gold,1500,'switching back refunds the training fee difference');
C.settle(s,now+50000,false);assert.equal(C.boatManifest(s)[0].count,8);
let woundedCrew=C.createSave(now);woundedCrew.base[0].lvl=2;woundedCrew.army.rifle=5;woundedCrew.army.heavy=1;let refill=C.boatRefillQuote(woundedCrew,0),heavyRefill=C.boatRefillQuote(woundedCrew,1);assert.equal(refill.count,3);assert.equal(heavyRefill.count,3);assert.equal(refill.cost,3*C.UNIT.rifle.cost);let beforeRefillGold=woundedCrew.resources.gold;assert.match(C.refillBoat(woundedCrew,0,now),/补 3 人/);assert.match(C.refillBoat(woundedCrew,1,now),/补 3 人/,'different boats refill in parallel');assert.match(C.upgradeUnit(woundedCrew,'rifle',now),/训练升级中/,'boat loading is independent from the training-upgrade slot');assert.equal(woundedCrew.craft.refills.length,2);assert.equal(woundedCrew.training.length,1);assert.equal(C.refillBoat(woundedCrew,0,now),'这艘艇正在上人');assert.equal(C.boatManifest(woundedCrew)[0].count,5);assert.ok(woundedCrew.resources.gold<beforeRefillGold);let loading=C.loadSave({getItem:()=>JSON.stringify(woundedCrew)},now+1000);assert.equal(loading.craft.refills.length,2);C.settle(loading,now+Math.max(refill.seconds,heavyRefill.seconds)*1000,false);assert.deepEqual(C.boatManifest(loading).map(b=>b.count),[8,4,2]);assert.equal(loading.craft.refills.length,0);
let twoRifles=C.createSave(now);twoRifles.base[0].lvl=3;twoRifles.craft.count=4;twoRifles.craft.levels.push(1);twoRifles.craft.loadouts.push('rifle');twoRifles.army.rifle=11;assert.deepEqual(C.boatManifest(twoRifles).map(b=>b.count),[8,2,2,3]);let fillOther=C.boatRefillQuote(twoRifles,3);assert.equal(fillOther.count,5);C.refillBoat(twoRifles,3,now);C.settle(twoRifles,now+fillOther.seconds*1000,false);assert.deepEqual(C.boatManifest(twoRifles).map(b=>b.count),[8,2,2,8],'refill stays with selected boat when two boats use rifle');
for(let x of [-13.7,-10,0,10,13.7])assert.equal(C.canLandAt(x,10.2),true,'the whole southern beach');
for(let [x,z] of [[-14,10.2],[14,10.2],[0,9.6],[-16,0],[16,0],[0,14.5]])assert.equal(C.canLandAt(x,z),false,'no other shore');
let currentDepth=C.MAP.maxZ-C.MAP.minZ,previousArea=13.3*2*17.05;assert.ok(currentDepth>17.05*1.28,'island depth must grow materially beyond v0.5.2');assert.ok(C.MAP.buildX*2*currentDepth>previousArea*1.45,'buildable area must grow by roughly another half');assert.ok((C.MAP.buildX*2*currentDepth)/(18.8*12.05)>2.9,'buildable area is now nearly three times the original island');

let quotas=C.createSave(now);quotas.resources={gold:99999,wood:99999,steel:99999};
assert.equal(C.buildingLimit(quotas,'sniper'),3);
assert.equal(C.buildingLimit(quotas,'mg'),0);
assert.match(C.buildAt(quotas,'mg',8,0),/司令部 2 级解锁/);
assert.match(C.buildAt(quotas,'rocket',8,0),/司令部 5 级解锁/);
let buildingAt=now;
for(let [type,x,z] of [['gold',-8,4],['wood',8,4],['steel',0,-5.7],['sniper',-4,-2],['sniper',4,-2],['sniper',0,3.2]]){assert.match(C.buildAt(quotas,type,x,z,buildingAt),/开工/);buildingAt=quotas.base.at(-1).constructionEnd+1;C.settle(quotas,buildingAt,false)}
assert.match(C.buildAt(quotas,'sniper',8,-5),/已建满/);
assert.match(C.moveBuilding(quotas,6,4.2,-2),/已移动/);
assert.equal(C.validateLayout(quotas.base),true);
assert.ok(C.BUILDING_FOOTPRINT_PADDING>0,'new placements must reserve a visible gap around every footprint');assert.equal(C.validatePlacement([{id:1,type:'hq',x:0,z:0,lvl:1}],{id:2,type:'gold',x:2.75,z:0,lvl:1}),false,'a merely non-intersecting model gap is too tight for a new building');assert.equal(C.validatePlacement([{id:1,type:'hq',x:0,z:0,lvl:1}],{id:2,type:'gold',x:2.90,z:0,lvl:1}),true,'the padded footprint must still allow a modest usable gap');
quotas.base[0].lvl=2;
assert.equal(C.buildingLimit(quotas,'mg'),2);
assert.match(C.buildAt(quotas,'mg',8,-5,buildingAt),/开工/);
quotas.base[0].lvl=C.MAX_HQ_LEVEL;
assert.match(C.startUpgrade(quotas,1,now),/10 级/);

let early=C.createSave(now),resourcesBefore=early.resources.gold;
C.settle(early,now+60000,false);
assert.equal(early.uncollected.gold,0,'unbuilt mines cannot produce');
assert.match(C.buildAt(early,'gold',-8,4,now),/开工/);
C.settle(early,now+120000,false);
assert.ok(early.uncollected.gold>0);
let gain=C.collectResources(early);
assert.ok(gain.gold>0&&early.resources.gold>resourcesBefore-C.buildCost('gold')[0]);
assert.equal(C.trainingCost('rifle'),C.UNIT.rifle.cost);
assert.deepEqual(C.unitUpgradeCost('rifle',1).slice(1),[0,0],'troop upgrades only cost gold');
assert.equal(C.landingCost('rifle',8),0,'soldiers cost gold when loaded, not when deployed');
assert.ok(C.productionRate({type:'wood',lvl:1})>C.productionRate({type:'steel',lvl:1}),'wood must refill faster than steel');
assert.ok(C.buildCost('sniper')[2]>C.buildCost('sniper')[1],'steel surplus is consumed by construction instead of starving wood');
let localStock=C.createSave(now);localStock.base[0].lvl=2;localStock.base.push({id:2,type:'gold',x:-5,z:2,lvl:1,stored:C.resourceSiteCapacity({lvl:1})-1},{id:3,type:'gold',x:5,z:2,lvl:1,stored:0});C.settle(localStock,now+10000,false);assert.equal(localStock.base[1].stored,C.resourceSiteCapacity(localStock.base[1]),'a resource point stops at its own onsite capacity');assert.ok(localStock.base[2].stored>0,'another resource point keeps producing when its neighbor is full');let beforeUpgradeCap=C.resourceSiteCapacity(localStock.base[1]);localStock.base[1].lvl++;assert.equal(C.resourceSiteCapacity(localStock.base[1]),beforeUpgradeCap+C.RESOURCE_SITE_CAPACITY_PER_LEVEL,'upgrading a resource point expands its small onsite buffer by one level');
localStock.resources.gold=C.storage(localStock,'gold')-100;localStock.base[1].stored=250;localStock.base[2].stored=80;let partial=C.collectResources(localStock);assert.equal(partial.gold,100);assert.equal(localStock.base[1].stored,150);assert.equal(localStock.base[2].stored,80);assert.equal(Math.floor(localStock.uncollected.gold),230,'global storage overflow remains at the original resource sites');
let oldAggregate=C.createSave(now);delete oldAggregate.resourceSiteStorage;oldAggregate.base.push({id:2,type:'gold',x:-5,z:2,lvl:1},{id:3,type:'wood',x:5,z:2,lvl:1},{id:4,type:'steel',x:0,z:-5,lvl:1});oldAggregate.uncollected={gold:700,wood:650,steel:625};let migratedStock=C.loadSave({getItem:()=>JSON.stringify(oldAggregate)},now);assert.equal(migratedStock.resourceSiteStorage,true);assert.deepEqual(C.RES.map(key=>Math.floor(migratedStock.base.find(b=>b.type===key).stored)),[700,650,625]);assert.deepEqual(C.RES.map(key=>Math.floor(migratedStock.uncollected[key])),[700,650,625],'legacy aggregate production migrates back to the matching sites');
let duplicateIndustry=C.createSave(now);duplicateIndustry.base[0].lvl=6;duplicateIndustry.base.push({id:2,type:'wood',x:-8,z:3,lvl:1,stored:500},{id:3,type:'wood',x:8,z:3,lvl:3,stored:2800},{id:4,type:'wood',x:0,z:5,lvl:2,stored:700},{id:5,type:'steel',x:-6,z:-5,lvl:2,stored:950},{id:6,type:'steel',x:6,z:-5,lvl:1,stored:450});duplicateIndustry.upgrades.push({id:2,start:now,end:now+5000});let prunedIndustry=C.loadSave({getItem:()=>JSON.stringify(duplicateIndustry)},now);assert.deepEqual(prunedIndustry.base.filter(b=>b.type==='wood').map(b=>[b.id,b.lvl,b.stored]),[[3,3,4000]],'old saves must keep only the highest-level lumber mill and merge all onsite wood');assert.deepEqual(prunedIndustry.base.filter(b=>b.type==='steel').map(b=>[b.id,b.lvl,b.stored]),[[5,2,1400]],'old saves must keep only the highest-level steelworks and merge all onsite steel');assert.ok(!prunedIndustry.upgrades.some(u=>u.id===2),'a removed duplicate resource building left a dangling upgrade');assert.match(prunedIndustry.migrationNotice,/拆除多余伐木场×2、钢厂×1/);

for(let level=1;level<=C.MAX_HQ_LEVEL;level++){let state=C.createSave(now);state.base[0].lvl=level;state.base.push({id:2,type:'vault',x:-5,z:-5,lvl:level});let before=C.clone(state);assert.equal(C.buildAt(state,'vault',5,-5,now),'保险库全基地最多一座');assert.deepEqual(state,before,'duplicate vault must not spend resources or create a job')}
let duplicateVaults=C.createSave(now);duplicateVaults.base[0].lvl=10;duplicateVaults.base.push({id:2,type:'vault',x:-8,z:4,lvl:1},{id:3,type:'vault',x:0,z:4,lvl:5},{id:4,type:'vault',x:8,z:4,lvl:2},{id:5,type:'gold',x:-8,z:-5,lvl:1,stored:0},{id:6,type:'wood',x:0,z:-5,lvl:1,stored:0},{id:7,type:'steel',x:8,z:-5,lvl:1,stored:0});duplicateVaults.upgrades.push({id:4,start:now,end:now+5000});duplicateVaults.resources={gold:9000,wood:9000,steel:9000};let expectedVaultRefund=C.RES.map((key,i)=>C.buildCost('vault',0)[i]+C.buildCost('vault',2)[i]+C.upgradeCost({type:'vault',lvl:1})[i]+C.upgradeCost({type:'vault',lvl:2})[i]);let normalizedVaults=C.loadSave({getItem:()=>JSON.stringify(duplicateVaults)},now);assert.deepEqual(normalizedVaults.base.filter(b=>b.type==='vault').map(b=>[b.id,b.lvl]),[[3,5]],'migration keeps only the highest-level vault');assert.ok(!normalizedVaults.upgrades.some(u=>u.id===4),'removed vault must leave no dangling upgrade');assert.deepEqual(C.RES.map((key,i)=>normalizedVaults.resources[key]+normalizedVaults.uncollected[key]),C.RES.map((key,i)=>duplicateVaults.resources[key]+expectedVaultRefund[i]),'inventory overflow and the full refund must remain collectible after reducing vault capacity');assert.ok(C.RES.every(key=>normalizedVaults.resources[key]<=C.storage(normalizedVaults,key)),'lower vault capacity cannot leave inventory exposed to later cap truncation');let reloadedVaults=C.loadSave({getItem:()=>JSON.stringify(normalizedVaults)},now);assert.deepEqual(reloadedVaults.uncollected,normalizedVaults.uncollected,'migration refund is applied only once');
let ware=C.createSave(now);assert.equal(C.buildingLimit(ware,'gold_store'),1);assert.equal(C.buildingLimit(ware,'vault'),1);
assert.match(C.buildAt(ware,'gold_store',-5,-4,now),/开工/);assert.equal(C.storage(ware,'gold',now+1000),1800,'unfinished treasury offers no capacity');let vaultAt=ware.base.at(-1).constructionEnd+1;assert.match(C.buildAt(ware,'vault',5,-4,vaultAt),/开工/);
assert.equal(C.storage(ware,'gold',vaultAt+1000),3100,'unfinished vault must not add its own storage');assert.equal(C.storage(ware,'wood',vaultAt+1000),1800,'unfinished vault leaked capacity to other resources');
C.settle(ware,now+30000,false);assert.equal(C.storage(ware,'gold',now+30000),3550);assert.equal(C.storage(ware,'wood',now+30000),2250);assert.equal(C.storage(ware,'steel',now+30000),2250);
let upgradedVault=C.clone(ware);upgradedVault.base.find(b=>b.type==='vault').lvl=2;assert.equal(C.storage(upgradedVault,'wood',now+30000),2700,'vault upgrades must expand their own three-resource storage');
ware.resources={gold:1000,wood:1000,steel:1000};let safe=C.raidProtection(ware,'gold');assert.equal(safe.base,568);assert.equal(safe.flat,300);assert.equal(safe.percent,.07);assert.equal(safe.total,938);
ware.base.push({id:4,type:'gold',x:-7,z:3,lvl:1,stored:3000},{id:5,type:'wood',x:7,z:3,lvl:1,stored:3000},{id:6,type:'steel',x:0,z:-6,lvl:1,stored:3000});C.syncUncollected(ware);let collected=C.collectResources(ware);assert.deepEqual(collected,{gold:2550,wood:1250,steel:1250},'dedicated stores and vault capacity remain independent while leftovers stay onsite');assert.deepEqual(ware.base.slice(-3).map(b=>b.stored),[450,1750,1750]);
let wasRaided=false;for(let seed=1;seed<=30&&!wasRaided;seed++){
 let settlement=C.clone(ware);settlement.seed=seed;settlement.raidAt=now;
 let before=Object.fromEntries(C.RES.map(k=>[k,{quantity:settlement.resources[k],safe:C.raidProtection(settlement,k).total}]));
 let rep=C.simulateRaid(settlement,now+60000);
 if(rep.outcome==='失守'){wasRaided=true;for(let k of C.RES){assert.equal(rep.lost[k],Math.floor((before[k].quantity-before[k].safe)*.14),'NPC only raids unprotected '+k);assert.equal(settlement.resources[k],before[k].quantity-rep.lost[k])}}
}
assert.equal(wasRaided,true,'unprotected HQ can be raided');
let legacyStore=C.createSave(now);legacyStore.base.push({id:2,type:'store',x:5,z:-4,lvl:1});assert.equal(C.storage(legacyStore,'gold'),3100);assert.equal(C.storage(legacyStore,'wood'),3100);assert.match(C.buildAt(legacyStore,'store',-5,-4,now),/不合法/);
let site=C.createSave(now);assert.match(C.buildAt(site,'gold',-8,4,now),/开工/);let buildEnd=site.base[1].constructionEnd;
let serial=C.createSave(now);assert.match(C.buildAt(serial,'gold',-8,4,now),/开工/);
let goldBeforeSecond=serial.resources.gold;assert.match(C.buildAt(serial,'wood',8,4,now+1000),/建造和升级共用一位/);
assert.equal(serial.base.length,2,'cannot open a second building site');assert.equal(serial.resources.gold,goldBeforeSecond,'blocked site takes no resources');
assert.match(C.buildAt(serial,'wood',8,4,serial.base[1].constructionEnd+1),/开工/,'the next building starts as soon as the first finishes');
assert.equal(buildEnd-now,C.buildDuration('gold',1)*1000);C.settle(site,now+3000,false);assert.equal(site.uncollected.gold,0,'unfinished mine produces nothing');
let restoredSite=C.loadSave({getItem:()=>JSON.stringify(site)},now+5000);assert.ok(restoredSite.base[1].constructionEnd,'reload preserves unfinished construction');
let siteBattle=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'mg',x:0,z:0,lvl:1,constructionEnd:buildEnd}],88,'defense');siteBattle.deploy('rifle',1,false,1,0);siteBattle.step();assert.equal(siteBattle.units[0].hp,siteBattle.units[0].maxHp,'construction site cannot fire');assert.equal(siteBattle.snapshot().base[1].site,true,'site state persists into replays');
C.settle(site,buildEnd+5000,false);assert.equal(site.base[1].constructionEnd,undefined);assert.ok(site.uncollected.gold>0&&site.uncollected.gold<5,'offline production starts only on completion');
let savedRefit=C.createSave(now);assert.equal(C.setBoatLoadout(savedRefit,0,'heavy',now).ok,true);let loadedRefit=C.loadSave({getItem:()=>JSON.stringify(savedRefit)},now+1000);assert.equal(C.boatManifest(loadedRefit)[0].count,0,'reload preserves crew wait');

let e=C.generateEnemy(100,2);
assert.ok(e&&C.validateLayout(e.base));
for(let level=1;level<=C.MAX_HQ_LEVEL;level++){let island=C.generateEnemy(900+level,level),minimum=C.npcBuildCounts(level),maximum=C.HQ_BUILD_LIMITS[level];for(let [type,count] of Object.entries(minimum)){let actual=island.base.filter(b=>b.type===type).length;assert.ok(actual>=count&&actual<=maximum[type],`NPC HQ${level} ${type} count must stay between its prerequisite floor and current quota`)}assert.ok(island.qualification.average>=island.qualification.minimumAverage,`NPC HQ${level} must satisfy its own average-level gate`);assert.ok(Object.values(island.training.units).every(v=>v>=island.qualification.minimumAverage));assert.ok(Object.values(island.training.weapons).every(v=>v>=Math.min(C.MAX_WEAPON_LEVEL,island.qualification.minimumAverage)))}
{let island=C.generateEnemy(901,1),hq=island.base.find(b=>b.type==='hq');assert.ok(Math.max(...island.base.map(b=>C.distance(b,hq)))<6.5,'low-level NPC buildings must form a compact mutually supporting position instead of isolated map-edge targets');let defenses=island.base.filter(b=>C.BUILD[b.type].damage);assert.ok(defenses.filter(a=>defenses.some(b=>a!==b&&C.distance(a,b)<8.2)).length===defenses.length,'every low-level NPC defense needs overlapping fire support')}
{let profiles={rushed:0,developed:0,fortified:0},averages={rushed:0,developed:0,fortified:0},sizes={rushed:0,developed:0,fortified:0};for(let seed=0;seed<1000;seed++){let island=C.generateEnemy(seed,10),profile=island.qualification.developmentProfile;profiles[profile]++;averages[profile]+=island.qualification.average;sizes[profile]+=island.base.length}assert.ok(profiles.rushed>=90&&profiles.rushed<=180,'rushed NPCs should remain an occasional draw, not the whole ladder: '+JSON.stringify(profiles));assert.ok(profiles.developed>=620&&profiles.developed<=760,'most NPCs should be normally developed: '+JSON.stringify(profiles));assert.ok(profiles.fortified>=120&&profiles.fortified<=230,'fortified NPCs should appear regularly: '+JSON.stringify(profiles));assert.ok(averages.developed/profiles.developed>averages.rushed/profiles.rushed+1.2,'developed NPCs are not materially stronger than rushed ones');assert.ok(averages.fortified/profiles.fortified>averages.developed/profiles.developed+.45,'fortified NPCs are not materially stronger than developed ones');assert.ok(sizes.developed/profiles.developed>sizes.rushed/profiles.rushed+3,'normally developed NPCs still hug the rushed building-count floor');assert.ok(sizes.fortified/profiles.fortified>=sizes.developed/profiles.developed,'fortified NPCs should not field fewer buildings than developed NPCs')}
let tierFive=C.generateEnemy(505,5),tierFiveMinimum=1+Object.values(C.npcBuildCounts(5)).reduce((a,b)=>a+b,0),tierFiveMaximum=1+Object.values(C.HQ_BUILD_LIMITS[5]).reduce((a,b)=>a+b,0);assert.ok(tierFive.base.length>=tierFiveMinimum&&tierFive.base.length<=tierFiveMaximum,'HQ5 building count must stay between its prerequisite floor and current quota');assert.ok(tierFive.base.filter(b=>b.type==='rocket').length>=1);assert.ok(tierFive.base.filter(b=>b.type==='wood').length>=1);assert.ok(tierFive.base.filter(b=>b.type==='steel').length>=1);for(let type of ['gold','wood','steel','gold_store','wood_store','steel_store','vault','sniper','mg','mortar','cannon'])assert.ok(tierFive.base.some(b=>b.type===type),'HQ5 lacks prerequisite '+type);
for(let i=0;i<24000;i++){let island=C.generateEnemy(i,i%10+1);assert.ok(island,'invalid layout seed '+i);assert.ok(island.qualification.average>=island.qualification.minimumAverage,'unqualified NPC seed '+i)}
for(let i=0;i<240;i++){let island=C.generateEnemy(i,5),hq=island.base.find(v=>v.type==='hq');assert.ok(island.base.filter(v=>v.type==='rocket').every(v=>v.z<=hq.z-.6));assert.ok(island.base.filter(v=>v.type==='mortar').some(v=>v.z<=hq.z+.4))}
assert.equal(C.BUILD.rocket.volley,4);
assert.equal(C.BUILD.rocket.period+1,150,'rocket volley reloads for five seconds at 30 Hz');
assert.ok(C.BUILD.rocket.range>C.BUILD.mortar.range);
assert.ok(C.BUILD.rocket.min>C.BUILD.mortar.min);
assert.deepEqual([C.BUILD.sniper.range,C.BUILD.mg.range,C.BUILD.mortar.range,C.BUILD.cannon.range,C.BUILD.rocket.range],[8.16,6.84,8.16,6.84,14.4],'all five defensive outer ranges must increase by exactly twenty percent');assert.deepEqual([C.BUILD.mortar.min,C.BUILD.rocket.min],[2.04,5.28],'the two real defensive blind zones must increase by exactly twenty percent');assert.equal(C.BUILD.rocket.splash,.95,'defensive rocket impacts have a meaningful blast radius');
assert.ok(C.BUILD.missile.range>C.BUILD.cannon.range,'anti-tank missiles must outrange the cannon');assert.equal(C.BUILD.missile.period+1,270,'anti-tank missiles reload for nine seconds at 30 Hz');assert.ok(C.BUILD.missile.damage>C.BUILD.cannon.damage,'anti-tank missile nominal damage must exceed the cannon');
let equalTank={type:'tank',level:6,maxHp:Math.round(C.UNIT.tank.hp*1.5)},lowerTank={type:'tank',level:5,maxHp:Math.round(C.UNIT.tank.hp*1.4)};assert.equal(C.missileDamage(6,equalTank),Math.ceil(equalTank.maxHp*.88),'an equal-level missile hit removes 88 percent max tank health');assert.ok(C.missileDamage(6,lowerTank)>lowerTank.maxHp,'a lower-level tank is destroyed by one missile');for(let type of ['rifle','heavy','rocket','medic']){let infantry={type,level:10,maxHp:Math.round(C.UNIT[type].hp*1.9)};assert.ok(C.missileDamage(1,infantry)>infantry.maxHp,`missile must one-shot ${type}`)}
let traverseTicks={};for(let type of ['mg','sniper','mortar','cannon','rocket','missile']){let state={heading:0,turnVelocity:0},speeds=[];for(let tick=1;tick<500;tick++){let done=C.advanceWeaponHeading(state,2.8,C.BUILD[type],C.DT);speeds.push(Math.abs(state.turnVelocity));if(!done)continue;let moving=speeds.filter(v=>v>1e-8),peak=Math.max(...moving),rated=Math.PI/C.BUILD[type].turn180;assert.ok(moving[0]<peak*.2,`${type} traverse must ease in below rated speed`);assert.ok(moving.at(-1)<peak*.6,`${type} traverse must ease out before alignment`);assert.ok(peak<=rated+1e-12,`${type} traverse exceeded its rated angular speed`);traverseTicks[type]=tick;break}assert.ok(traverseTicks[type],`${type} traverse did not finish`)}assert.ok(traverseTicks.mg<traverseTicks.sniper&&traverseTicks.sniper<traverseTicks.mortar&&traverseTicks.mortar<traverseTicks.cannon&&traverseTicks.cannon<traverseTicks.rocket&&traverseTicks.rocket<traverseTicks.missile,'every defense needs its own ordered traverse time');
assert.ok(C.UNIT.heavy.speed>C.UNIT.rifle.speed&&C.UNIT.heavy.speed>C.UNIT.medic.speed,'the heavy gunner must reach the front before riflemen and medics instead of lagging behind its own shield line');
assert.ok(C.rocketScatterRadius(14,C.BUILD.rocket.range)>C.rocketScatterRadius(5.6,C.BUILD.rocket.range)*4);
let nearHits=0,farHits=0,nearError=0,farError=0;
for(let seed=0;seed<100;seed++)for(let [x,acc] of [[5.6,'near'],[13.8,'far']]){
 let arc=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],seed,'defense',null,1,C.MAP.spawnZ,24);arc.deploy('rifle',x,false,1,0);arc.step();
 assert.equal(arc.projectiles.length,4,'one volley has four independent missiles');
 assert.ok(arc.projectiles.every(p=>p.weapon==='rocket'&&p.radius===C.BUILD.rocket.splash&&p.land>arc.tick&&p.start>=arc.tick));
 let error=arc.projectiles.reduce((n,p)=>n+C.distance(p,{x,z:0}),0)/4;if(acc==='near')nearError+=error;else farError+=error;
 assert.equal(arc.units[0].hp,arc.units[0].maxHp,'rocket damage waits until impact');
 for(let t=0;t<42;t++){arc.units[0].x=x;arc.units[0].z=0;arc.step()}
 if(arc.units[0].hp<arc.units[0].maxHp){if(acc==='near')nearHits++;else farHits++}
}
assert.equal(nearHits,100,'inside the allowed range, close salvos reliably land');
assert.ok(farHits<nearHits&&farHits>30,'distant salvos miss more often: '+farHits);
assert.ok(farError>nearError*3,'longer range increases impact scatter');
let rocketSplash=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],18,'defense',null,1,C.MAP.spawnZ,24);rocketSplash.deploy('rifle',5.6,false,1,0);rocketSplash.deploy('rifle',6.0,false,1,0);rocketSplash.step();rocketSplash.projectiles.forEach((p,i)=>{p.x=i?8:5.6;p.z=i?8:0;p.land=rocketSplash.tick+1});rocketSplash.step();assert.ok(rocketSplash.units.every(u=>u.hp<u.maxHp),'rocket damage is resolved around the scattered impact and can hurt adjacent troops');
let blind=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],46,'defense');blind.deploy('rifle',1.4,false,1,0);blind.step();assert.equal(blind.projectiles.length,0,'rocket launcher has a medium blind spot');
let nearest=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],46,'defense',null,1,C.MAP.spawnZ,24);nearest.deploy('rifle',5.6,false,1,0);nearest.deploy('rifle',10,false,1,0);nearest.step();assert.ok(nearest.projectiles.every(p=>C.distance(p,{x:5.6,z:0})<C.distance(p,{x:10,z:0})),'rockets aim at the nearest legal target');
assert.equal(nearest.base[1].aimX,5.6);assert.equal(nearest.base[1].aimZ,0);nearest.units[0].x=5.8;nearest.step();assert.equal(nearest.base[1].aimX,5.8,'defense turret tracks its locked target while reloading');
let locked=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'sniper',x:0,z:0,lvl:1}],91,'defense');locked.deploy('heavy',4,false,1,0);locked.deploy('heavy',5,false,1,0);locked.step();assert.equal(locked.base[1].targetId,1);locked.units[1].x=2.5;locked.step();assert.equal(locked.base[1].targetId,1,'a closer unit cannot steal an active lock');locked.units[0].x=8.4;locked.step();assert.equal(locked.base[1].targetId,2,'leaving the legal range releases the lock');assert.equal(locked.useSkill('shock',0,0),true);let shockEvent=locked.events.find(e=>e.kind==='shock');assert.equal(shockEvent.land-shockEvent.start,18,'shock shell flight must sync with its delayed impact sound');assert.equal(shockEvent.ttl,42,'shock effect must keep its post-impact ground arcs');assert.equal(locked.base[1].targetId,undefined,'shock immediately releases the target');locked.step();assert.equal(locked.base[1].targetId,undefined,'a stunned defense cannot acquire another target');
let troopLock=new C.Battle([{id:1,type:'hq',x:-3,z:0,lvl:1},{id:2,type:'gold',x:3,z:0,lvl:1}],22);troopLock.deploy('rifle',-1,false,1,0);troopLock.step();assert.equal(troopLock.units[0].targetId,1);troopLock.units[0].x=3;troopLock.step();assert.equal(troopLock.units[0].targetId,1,'troops keep attacking their locked building until it dies');
assert.ok(C.BUILD.mg.range<C.BUILD.sniper.range&&C.BUILD.mg.range>6,'machine gun reaches almost as far as the sniper tower');let mgClose=0,mgFar=0;for(let seed=0;seed<100;seed++)for(let [x,label] of [[1,'close'],[6.4,'far']]){let lane=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'mg',x:0,z:0,lvl:1}],seed,'defense',null,1,C.MAP.spawnZ,24);lane.deploy('rifle',x,false,1,0);lane.step();if(lane.units[0].hp<lane.units[0].maxHp){if(label==='close')mgClose++;else mgFar++}}
assert.equal(mgClose,100);assert.ok(mgFar<30,'long-range machine-gun fire must be very inaccurate: '+mgFar);
let stray=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'mg',x:0,z:0,lvl:1}],3,'defense',null,1,C.MAP.spawnZ,24);stray.deploy('rifle',6.06,false,1,0);stray.deploy('rifle',6.06,false,1,.72);stray.step();assert.equal(stray.units[0].hp,stray.units[0].maxHp);assert.ok(stray.units[1].hp<stray.units[1].maxHp,'a scattered machine-gun round can hit the neighboring unit instead of its lock');
let mort=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'mortar',x:0,z:0,lvl:1}],29,'defense',null,1,C.MAP.spawnZ,24);mort.deploy('rifle',1,false,1,0);mort.step();assert.equal(mort.projectiles.length,0,'mortar has a minimum range blind spot');mort.deploy('rifle',4,false,1,0);mort.step();assert.equal(mort.projectiles.length,1);assert.equal(mort.projectiles[0].x,4,'mortar targets nearest valid unit');assert.ok(mort.projectiles[0].land>mort.tick+50,'new mortar arc stays visible instead of teleporting');assert.equal(mort.units[1].hp,mort.units[1].maxHp,'mortar shell is not instantaneous');
let splash=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'mortar',x:0,z:0,lvl:1}],31,'defense',null,1,C.MAP.spawnZ,24);splash.deploy('heavy',4,false,1,0);splash.deploy('rifle',4.1,false,1,0);splash.step();let firstMortar=splash.projectiles[0],untilImpact=firstMortar.land-splash.tick;for(let i=0;i<untilImpact;i++){splash.units[0].x=4;splash.units[0].z=0;splash.units[1].x=4.1;splash.units[1].z=0;splash.step()}assert.ok(Math.abs(splash.units[0].maxHp-splash.units[0].hp-C.BUILD.mortar.damage*.72)<.001,'heavy has visible protection against mortar splash');assert.equal(splash.units[1].maxHp-splash.units[1].hp,C.BUILD.mortar.damage,'rifle still takes full splash damage');
let gunTest=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],42);
assert.equal(gunTest.fire(0,0),true);assert.equal(gunTest.gunboatShells.length,1);
for(let t=0;t<27;t++)gunTest.step();assert.equal(gunTest.base[0].hp,gunTest.base[0].maxHp,'artillery damage follows visible flight');
gunTest.step();assert.equal(gunTest.base[0].hp,gunTest.base[0].maxHp-C.gunboatDamage('fire',1));
assert.ok(gunTest.events.some(v=>v.kind==='blast'&&v.radius===C.SKILLS.fire.radius));
assert.equal(gunTest.useSkill('barrage',0,0),true);
let ten=C.clone(gunTest.gunboatShells);assert.equal(ten.length,10,'gunboat volley fires ten light rockets');
assert.ok(ten.every(p=>p.kind==='barrage'&&p.damage===C.gunboatDamage('barrage',1)&&p.radius===1.15&&p.land>gunTest.tick));
assert.equal(C.SKILLS.fire.maxBuildings,4,'artillery must cap one shell at four tightly packed buildings');assert.ok(C.SKILLS.barrage.radius>0,'every barrage rocket must retain its own area damage');
assert.ok(ten.some(p=>C.distance(p,{x:0,z:0})>p.radius),'gunboat rockets must no longer guarantee several pinpoint hits at long range');
assert.ok(ten[0].land-gunTest.tick>=35&&ten.at(-1).land-gunTest.tick>=80,'rockets take visibly longer to arrive');
assert.ok(C.gunboatRocketSpread(0,-5)>C.gunboatRocketSpread(0,5),'far targets have wider gunboat barrage scatter');
assert.ok(C.gunboatRocketDispersion(0,0,1)>C.gunboatFireDispersion(0),'a stabilized rocket barrage must still be much less accurate than rushed naval artillery');assert.ok(C.gunboatRocketDispersion(0,0,0)>C.gunboatRocketDispersion(0,0,1)&&C.gunboatFireDispersion(0)>C.gunboatFireDispersion(1),'holding the pointer still must visibly tighten both weapon footprints');
let same=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],42);same.fire(0,0);for(let t=0;t<28;t++)same.step();same.useSkill('barrage',0,0);assert.deepEqual(same.gunboatShells,ten,'seed and command time reproduce impacts');
let cannon=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'cannon',x:0,z:0,lvl:1}],29,'defense',null,1,C.MAP.spawnZ,24);
cannon.deploy('heavy',3,false,1,0);cannon.deploy('heavy',3.1,false,1,0);cannon.step();assert.equal(cannon.projectiles.length,1);assert.equal(cannon.projectiles[0].targetId,1);assert.ok(cannon.projectiles[0].land>cannon.tick);
for(let t=0;t<20;t++)cannon.step();assert.equal(cannon.units[0].hp,cannon.units[0].maxHp-C.BUILD.cannon.damage*1.2,'cannon one-shots ordinary infantry with its anti-personnel multiplier');assert.equal(cannon.units[1].hp,cannon.units[1].maxHp,'cannon has no splash damage');
for(let level=1;level<=C.MAX_HQ_LEVEL;level++){let tankHp=Math.round(C.UNIT.tank.hp*(1+.10*(level-1))),same=C.BUILD.cannon.damage*(1+.12*(level-1));assert.ok(same*2<tankHp&&same*3>=tankHp,'same-level cannon must destroy a tank in exactly three hits at level '+level);if(level<C.MAX_HQ_LEVEL){let higher=C.BUILD.cannon.damage*(1+.12*level);assert.ok(higher*2>=tankHp,'a cannon one level higher must destroy the tank in two hits at level '+level)}}
let cannonTank=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'cannon',x:0,z:0,lvl:1}],30,'replay',null,1,C.MAP.spawnZ,24);cannonTank.deploy('tank',3,false,1,0);cannonTank.step();assert.equal(cannonTank.projectiles[0].damage,C.BUILD.cannon.damage,'tank takes the base cannon damage');let oldCannon=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'cannon',x:0,z:0,lvl:1}],30,'replay',null,1,8.6,11);oldCannon.deploy('tank',3,false,1,0);oldCannon.step();assert.equal(oldCannon.projectiles[0].damage,170,'v11 reports retain their original cannon damage');let oldRocket=new C.Battle([{id:1,type:'hq',x:9,z:-6,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],31,'replay',null,1,8.6,11);oldRocket.deploy('rifle',8.5,false,1,0);oldRocket.step();assert.equal(oldRocket.projectiles.length,4);assert.ok(oldRocket.projectiles.every(p=>p.radius===.62),'v11 reports retain the former rocket range and splash');let rocketBase=[{id:1,type:'hq',x:20,z:-6,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],v16Rocket=new C.Battle(rocketBase,31,'replay',null,1,C.MAP.spawnZ,16),v20Rocket=new C.Battle(rocketBase,31,'replay',null,1,C.MAP.spawnZ,20),currentRocket=new C.Battle(rocketBase,31,'replay',null,1,C.MAP.spawnZ,24);v16Rocket.deploy('rifle',13.2,false,1,0);v20Rocket.deploy('rifle',13.2,false,1,0);currentRocket.deploy('rifle',13.2,false,1,0);v16Rocket.step();v20Rocket.step();currentRocket.step();assert.equal(v16Rocket.projectiles.length,0,'v16 replay keeps the former 8.0 rocket range');assert.equal(v20Rocket.projectiles.length,0,'v20 replay keeps the shipped 12.0 rocket range');assert.equal(currentRocket.projectiles.length,4,'v21 rocket launcher reaches its twenty-percent-longer outer range');let v16Blind=new C.Battle(rocketBase,32,'replay',null,1,C.MAP.spawnZ,16),v20Blind=new C.Battle(rocketBase,32,'replay',null,1,C.MAP.spawnZ,20),currentBlind=new C.Battle(rocketBase,32);v16Blind.deploy('rifle',4.8,false,1,0);v20Blind.deploy('rifle',4.8,false,1,0);currentBlind.deploy('rifle',4.8,false,1,0);v16Blind.step();v20Blind.step();currentBlind.step();assert.equal(v16Blind.projectiles.length,4,'v16 replay keeps the former 2.8 blind spot');assert.equal(v20Blind.projectiles.length,4,'v20 replay keeps the shipped 4.4 blind spot');assert.equal(currentBlind.projectiles.length,0,'v21 rocket launcher uses the twenty-percent-larger 5.28 blind spot');
const heldUnit=(id,type,x,z,level=1)=>{let maxHp=Math.round(C.UNIT[type].hp*(1+.10*(level-1)));return {id,type,x,z,level,hp:maxHp,maxHp,cool:1e9,walk:0,runUntil:0}};
assert.deepEqual([1,2,4,7].map(C.rocketTubeCount),[1,4,6,8],'rocket launchers progress from one to four, six and eight tubes');assert.deepEqual([1,2,4,7].map(C.missileTubeCount),[1,2,3,4],'missile launchers stay below rocket count and cap at four tubes');assert.deepEqual([1,3,5,7].map(C.machineGunBarrelCount),[1,2,4,6],'machine guns progress from one to six barrels');assert.deepEqual([1,4,7].map(C.cannonBarrelCount),[1,2,3],'naval cannons cap at three barrels');
const primedDefense=(type,level,ruleset=26)=>{let fight=new C.Battle([{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type,x:0,z:0,lvl:level}],700+level,'defense',null,1,C.MAP.spawnZ,ruleset),target={id:1,type:'tank',x:6,z:0,level,hp:100000,maxHp:100000,cool:1e9,walk:0,runUntil:0},weapon=fight.base[1];fight.units.push(target);weapon.targetId=target.id;weapon.heading=Math.PI/2;weapon.turnVelocity=0;weapon.lockReady=true;weapon.lockStart=-100;weapon.cool=0;return {fight,target,weapon}};
for(let level of [1,2,4,7]){let {fight,weapon}=primedDefense('rocket',level);fight.step();let tubes=C.rocketTubeCount(level),volley=fight.projectiles.filter(p=>p.weapon==='rocket'),expected=C.BUILD.rocket.damage*(1+.12*(level-1))*4;assert.equal(volley.length,tubes,`rocket Lv.${level} must fire every loaded tube`);assert.ok(Math.abs(volley.reduce((sum,p)=>sum+p.damage,0)-expected)<1e-9,`rocket Lv.${level} must divide, not multiply, total volley damage`);assert.deepEqual(volley.map(p=>p.lane),Array.from({length:tubes},(_,i)=>i));assert.equal(weapon.cool,C.BUILD.rocket.period,'tube count must not change rocket reload time')}
{let {fight,target,weapon}=primedDefense('missile',7);fight.step();weapon.cool=0;fight.step();let shots=fight.projectiles.filter(p=>p.weapon==='missile');assert.equal(shots.length,2,'a four-tube missile rack still fires only one missile per attack');assert.deepEqual(shots.map(p=>p.lane),[0,1],'missiles must rotate through tube positions in order');assert.ok(shots.every(p=>p.tubeCount===4&&p.damage===C.missileDamage(7,target)),'missile damage must remain whole rather than being split by tube count')}
{let {fight,weapon}=primedDefense('cannon',7);fight.step();weapon.cool=0;fight.step();let shots=fight.projectiles.filter(p=>p.weapon==='cannon');assert.equal(shots.length,2,'a triple cannon still fires one shell per attack');assert.deepEqual(shots.map(p=>p.lane),[0,1],'cannon barrels must fire in sequence');assert.ok(shots.every(p=>p.tubeCount===3&&p.damage===C.BUILD.cannon.damage*(1+.12*6)),'cannon damage must not be multiplied or divided by barrel count');assert.equal(weapon.cool,C.BUILD.cannon.period,'cannon fire rate must not change with barrel count')}
{let {fight,weapon}=primedDefense('mg',7);fight.step();weapon.cool=0;fight.step();let shots=fight.events.filter(e=>e.kind==='hit'&&e.weapon==='mg');assert.deepEqual(shots.map(e=>e.lane),[0,1],'machine-gun barrels must fire in sequence');assert.ok(shots.every(e=>e.tubeCount===6),'late machine guns must expose all six visual barrels');assert.equal(weapon.cool,C.BUILD.mg.period,'machine-gun fire rate must stay unchanged')}
{let {fight}=primedDefense('missile',7,25);fight.step();assert.equal(fight.projectiles.filter(p=>p.weapon==='missile').length,1);assert.equal(fight.projectiles.find(p=>p.weapon==='missile').tubeCount,1,'v25 replay must retain its single missile muzzle');let snapshot=fight.snapshot();assert.equal(snapshot.version,25,'historical replay version must not be rewritten')}
{let cluster=[{id:1,type:'hq',x:10,z:10,lvl:1},{id:2,type:'gold',x:-.65,z:-.65,lvl:1},{id:3,type:'gold',x:.65,z:-.65,lvl:1},{id:4,type:'gold',x:-.65,z:.65,lvl:1},{id:5,type:'gold',x:.65,z:.65,lvl:1},{id:6,type:'gold',x:1.35,z:0,lvl:1}],artillery=new C.Battle(cluster,812);artillery.fire(0,0);for(let i=0;i<28;i++)artillery.step();assert.deepEqual(artillery.base.slice(1).map(b=>b.hp<b.maxHp),[true,true,true,true,false],'one gunboat shell must cover a tight 2×2 block but cap at four buildings');let barrage=new C.Battle(cluster,813);barrage.gunboatShells.push({x:0,z:0,kind:'barrage',radius:C.SKILLS.barrage.radius,damage:10,start:0,land:1,lane:0});barrage.step();assert.ok(barrage.base.slice(1).every(b=>b.hp<b.maxHp),'each individual barrage rocket must apply uncapped area damage')}
let missilePriority=new C.Battle([{id:1,type:'hq',x:12,z:-10,lvl:6},{id:2,type:'missile',x:0,z:0,lvl:6}],330,'defense'),nearInfantry=heldUnit(1,'rifle',5,0,6),farTank=heldUnit(2,'tank',6,0,6);missilePriority.units.push(nearInfantry,farTank);for(let i=0;i<300&&!missilePriority.projectiles.length;i++){missilePriority.step();nearInfantry.x=5;nearInfantry.z=0;farTank.x=6;farTank.z=0}assert.equal(missilePriority.base[1].targetId,nearInfantry.id,'anti-tank missile launcher must retain normal nearest-target priority');assert.equal(missilePriority.projectiles[0].targetId,nearInfantry.id);assert.equal(missilePriority.projectiles[0].weapon,'missile');
let trackingBattle=new C.Battle([{id:1,type:'hq',x:12,z:-10,lvl:1},{id:2,type:'cannon',x:0,z:0,lvl:1}],331,'defense'),trackingTarget=heldUnit(1,'tank',6,0);trackingBattle.units.push(trackingTarget);for(let i=0;i<250&&!trackingBattle.base[1].lockReady;i++){trackingBattle.step();trackingTarget.x=6;trackingTarget.z=0}let trackingGun=trackingBattle.base[1];assert.equal(trackingGun.lockReady,true,'first target must finish a real acquisition before firing');trackingGun.cool=0;trackingTarget.x=0;trackingTarget.z=6;let trackingShots=trackingBattle.projectiles.length,trackingHeading=trackingGun.heading;trackingBattle.step();assert.equal(trackingBattle.projectiles.length,trackingShots+1,'a completed lock must keep firing while the turret catches up to a moving target');assert.equal(trackingGun.lockReady,true,'tracking movement must not revoke a completed lock');assert.ok(trackingGun.heading<trackingHeading,'the barrel must visibly begin turning toward the moved target');
let handoffBattle=new C.Battle([{id:1,type:'hq',x:12,z:-10,lvl:1},{id:2,type:'cannon',x:0,z:0,lvl:1}],332,'defense'),firstTarget=heldUnit(1,'tank',6,0),closeTarget=heldUnit(2,'tank',12,0),farTarget=heldUnit(3,'tank',12,4);handoffBattle.units.push(firstTarget,closeTarget,farTarget);for(let i=0;i<250&&!handoffBattle.base[1].lockReady;i++){handoffBattle.step();firstTarget.x=6;firstTarget.z=0;closeTarget.x=12;closeTarget.z=0;farTarget.x=12;farTarget.z=4}let handoffGun=handoffBattle.base[1];firstTarget.hp=0;closeTarget.x=6;closeTarget.z=.2;handoffGun.cool=0;let closeShots=handoffBattle.projectiles.length;handoffBattle.step();assert.equal(handoffGun.targetId,closeTarget.id);assert.equal(handoffGun.lockReady,true,'tightly grouped targets must preserve completed lock');assert.equal(handoffBattle.projectiles.length,closeShots+1,'tightly grouped targets should hand off fire without a dead interval');closeTarget.hp=0;farTarget.x=0;farTarget.z=6;handoffGun.cool=0;let farShots=handoffBattle.projectiles.length;handoffBattle.step();assert.equal(handoffGun.targetId,farTarget.id);assert.equal(handoffGun.lockReady,false,'a large-angle target change must reacquire');assert.equal(handoffBattle.projectiles.length,farShots,'large-angle handoff must not fire instantly');
let reloadBattle=new C.Battle([{id:1,type:'hq',x:12,z:-10,lvl:1},{id:2,type:'cannon',x:0,z:0,lvl:1}],333,'defense'),reloadTarget=heldUnit(1,'tank',12,0);reloadBattle.units.push(reloadTarget);let reloadGun=reloadBattle.base[1];reloadGun.cool=10;for(let i=0;i<5;i++){reloadBattle.step();reloadTarget.x=12;reloadTarget.z=0}assert.equal(reloadGun.cool,5,'reload must continue while no target is in range');reloadTarget.x=6;reloadTarget.z=0;for(let i=0;i<3;i++){reloadBattle.step();reloadTarget.x=6;reloadTarget.z=0}assert.equal(reloadGun.cool,2,'reload must continue while traversing to the next target');assert.equal(reloadGun.lockReady,false,'turning time must not be skipped merely because reload is almost complete');
let historical=new C.Battle([{id:1,type:'hq',x:8,z:-6,lvl:1},{id:2,type:'mortar',x:0,z:0,lvl:1},{id:3,type:'cannon',x:0,z:1,lvl:1}],29,'replay',null,1,C.MAP.spawnZ,6);historical.deploy('heavy',4,false,1,0);historical.step();assert.equal(historical.projectiles.find(p=>p.weapon==='mortar').damage,60,'v6 mortar damage remains unchanged');assert.equal(historical.projectiles.find(p=>p.weapon==='cannon').damage,116,'v6 cannon damage remains unchanged');let oldHeavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,6);oldHeavy.deploy('heavy',0,false,1,2.5);oldHeavy.step();assert.equal(oldHeavy.base[0].maxHp-oldHeavy.base[0].hp,17,'v6 heavy keeps old gun damage');
let oldArtillery=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],42,'attack',null,1,C.MAP.spawnZ,4);oldArtillery.fire(0,0);assert.equal(oldArtillery.base[0].hp,oldArtillery.base[0].maxHp-190,'older replays retain instant artillery');
let b=new C.Battle(e.base,100,'attack',e.reward,5);
assert.equal(b.energy,C.boatEnergy(5));
assert.equal(b.landBoat('rifle',8,-10.6,0,1,true,10.3),true);
assert.equal(b.landBoat('rifle',8,-7.6,0),false);
assert.equal(b.landBoat('rifle',8,14,1),false);
assert.equal(b.landings[0].x,-10.6,'an open stretch of beach is used exactly where the flag was placed');assert.equal(b.landingFlags[0].x,-10.6);assert.equal(b.landingFlags[0].z,10.3);assert.equal(b.commands[0].z,10.3);
for(let i=0;i<71;i++)b.step();assert.equal(b.units.length,0);
b.step();assert.equal(b.units.length,3,'ramp first wave');
for(let i=0;i<5;i++)b.step();assert.equal(b.units.length,6,'second wave');
for(let i=0;i<5;i++)b.step();assert.equal(b.units.length,8,'third wave');
assert.ok(new Set(b.units.map(u=>u.x.toFixed(2))).size>=3,'troops do not emerge from one point');
assert.ok(b.units.every(u=>u.type==='rifle'&&u.x<0));
assert.ok(b.units.every(u=>u.landingFlagId===b.landingFlags[0].id),'disembarking troops receive their own rally flag');
assert.ok(b.units.every(u=>u.z>b.landingFlags[0].z+2),'troops leave the craft at the shoreline instead of the craft driving to the flag');
let berths=new C.Battle([{id:1,type:'hq',x:0,z:-6,lvl:1}],72);for(let i=0;i<5;i++)assert.equal(berths.landBoat('rifle',1,1.13,i,1,true,10.25),true);assert.equal(berths.landings[0].x,1.13,'continuous berth allocator preserves the requested point');assert.ok(berths.landings.every((l,i,a)=>a.every((q,j)=>i===j||Math.abs(l.x-q.x)>=C.LANDING_BOAT_SPACING-.001)),'boats reserve the nearest non-overlapping positions across the whole beach');assert.ok(berths.landingFlags.every(f=>f.x===1.13&&f.z===10.25),'berth displacement never moves the player flag');
let orderlyDeparture=new C.Battle([{id:1,type:'hq',x:20,z:20,lvl:1}],721);assert.equal(orderlyDeparture.landBoat('rifle',8,0,0,1,false,10.25),true);while(!orderlyDeparture.landings[0].released)orderlyDeparture.step();let finishedLanding=orderlyDeparture.landings[0],departAt=finishedLanding.departTick;assert.equal(finishedLanding.releasedCount,8,'landing craft cannot leave with troops still aboard');assert.equal(departAt,orderlyDeparture.tick+18,'empty craft must pause clear of disembarking troops before reversing');while(orderlyDeparture.tick<departAt+44)orderlyDeparture.step();assert.equal(orderlyDeparture.landings.length,1,'craft vanished before completing its straight reverse');orderlyDeparture.step();assert.equal(orderlyDeparture.landings.length,0,'empty craft must clear the shoreline after its departure window');
let goal=e.base.find(v=>v.type==='sniper');
assert.ok(b.flareAt(goal.x,goal.z,goal.id));
assert.equal(b.energy,b.maxEnergy-C.SKILLS.flare.cost);
assert.equal(b.flare.launched,b.tick);let flareEvent=b.events.find(v=>v.kind==='flare');assert.equal(flareEvent.start,b.tick);assert.equal(flareEvent.land,b.tick+14,'signal flare has a visible flight window before its marker burns');
assert.equal(b.useSkill('medkit',0,3),true);
assert.equal(b.medkits[0].drop,b.tick+60,'plane reaches the target before the crate appears');
assert.equal(b.medkits[0].land,b.tick+150);assert.equal(b.medkits[0].radius,C.SKILLS.medkit.radius);
assert.equal(b.useSkill('shock',goal.x,goal.z),true);
assert.ok(b.base.find(v=>v.id===goal.id).stunnedUntil>b.tick);
assert.equal(b.useSkill('barrage',goal.x,goal.z),true);
let commands=C.clone(b.commands),rep=b.snapshot();
for(let i=0;i<150&&!b.done;i++)b.step();
let replay=C.runCommands(new C.Battle(rep.base,rep.seed,'replay',null,rep.gunboatLevel),commands,b.tick);
assert.equal(replay.tick,b.tick);
assert.equal(replay.energy,b.energy);
assert.deepEqual(replay.base.map(v=>v.hp),b.base.map(v=>v.hp));

let solo=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],54);
solo.landBoat('rifle',3,0,0);
for(let i=0;i<360&&!solo.done;i++)solo.step();
let hq=solo.base[0];
assert.ok(hq.hp<hq.maxHp,'units can still shoot the HQ');
let alive=solo.units.filter(u=>u.hp>0);
if(alive.length)assert.ok(alive.every(u=>C.distance(u,hq)>=1.4),'units stop outside HQ geometry');
assert.ok(C.UNIT_COLLISION_RADIUS.tank>C.UNIT_COLLISION_RADIUS.heavy&&C.UNIT_COLLISION_RADIUS.heavy>C.UNIT_COLLISION_RADIUS.rifle,'collision volume must scale from infantry to heavy gunner to tank');
let corridorBase=[{id:1,type:'hq',x:0,z:-9,lvl:1},{id:2,type:'gold',x:-1.2,z:2,lvl:1},{id:3,type:'gold',x:1.2,z:2,lvl:1}],crossGap=type=>{let lane=new C.Battle(corridorBase,789,'attack');lane.deploy(type,0,false,1,8);lane.units[0].targetId=1;let crossing=null;for(let i=0;i<1000&&crossing===null;i++){let before=lane.units[0].z;lane.step();let unit=lane.units[0];for(let obstacle of lane.base.slice(1))assert.ok(C.distance(unit,obstacle)>=C.UNIT_COLLISION_RADIUS[type]+C.BUILD[obstacle.type].size*.55-.003,`${type} clipped through a building`);if(before>2&&unit.z<=2)crossing=unit.x}return crossing};
let rifleGap=crossGap('rifle'),tankGap=crossGap('tank');assert.ok(Math.abs(rifleGap)<.2,'riflemen should fit through a valid narrow building gap');assert.ok(Math.abs(tankGap)>2,'tank must reject the infantry-only gap and path around the buildings');
let crowdedTanks=new C.Battle([{id:1,type:'hq',x:0,z:-8,lvl:1}],456,'attack');for(let i=0;i<4;i++)crowdedTanks.deploy('tank',0,false,1,8);for(let i=0;i<5;i++)crowdedTanks.step();for(let i=0;i<crowdedTanks.units.length;i++)for(let j=i+1;j<crowdedTanks.units.length;j++)assert.ok(C.distance(crowdedTanks.units[i],crowdedTanks.units[j])>=C.UNIT_COLLISION_RADIUS.tank*2+.035,'tank collision bodies still overlap');
let oldCollision=new C.Battle([{id:1,type:'hq',x:0,z:-8,lvl:1}],457,'replay',null,1,C.MAP.spawnZ,22);assert.equal(oldCollision.unitRadius({type:'tank'}),.66,'v22 replay must keep the former tank collision body');assert.equal(crowdedTanks.unitRadius({type:'tank'}),C.UNIT_COLLISION_RADIUS.tank,'current battle must use the smaller model-matched tank body');
let beachCrowd=new C.Battle([{id:1,type:'hq',x:0,z:-10,lvl:99}],1255,'attack',null,1,C.MAP.spawnZ,23),arrivalDistances=[],rallyBefore=new Map();for(let [index,type,count] of [[0,'rifle',8],[1,'heavy',4],[2,'rocket',4],[3,'tank',1],[4,'medic',4]])assert.equal(beachCrowd.landBoat(type,count,0,index,1,false,10.25,8),true);for(let tick=0;tick<700;tick++){for(let u of beachCrowd.units)rallyBefore.set(u.id,!!u.landingRallyDone);beachCrowd.step();for(let u of beachCrowd.units)if(u.landingRallyDone&&!rallyBefore.get(u.id))arrivalDistances.push(Math.hypot(u.x-u.rallyX,u.z-u.rallyZ))}assert.equal(beachCrowd.units.length,21);assert.ok(beachCrowd.units.every(u=>u.landingRallyDone),'a crowded shared beach flag must release every surviving unit into combat');assert.ok(Math.min(...arrivalDistances)>1.8,'the rally flag regressed from a formation area to an impossible single point');let attackers=beachCrowd.units.filter(u=>u.type!=='medic');assert.ok(new Set(attackers.map(u=>Math.round(u.approachAngle*100))).size>=12,'units targeting one building must spread across distinct firing positions');assert.ok(attackers.some(u=>(u.approachTurns||0)>0),'a blocked firing lane must rotate around the same locked target');for(let i=0;i<beachCrowd.units.length;i++)for(let j=i+1;j<beachCrowd.units.length;j++){let a=beachCrowd.units[i],b=beachCrowd.units[j];assert.ok(C.distance(a,b)>=C.UNIT_COLLISION_RADIUS[a.type]+C.UNIT_COLLISION_RADIUS[b.type]+.035,'smaller troops may not overlap while rerouting')}
let carry=C.createSave(now),soft={base:[{id:1,type:'hq',x:0,z:0,lvl:1}],reward:{gold:200,wood:100,steel:50}};
let sortie=C.runCommands(new C.Battle(soft.base,54,'attack',soft.reward),[{kind:'land',type:'rifle',count:8,index:0,x:0,level:1,t:0}]);
assert.equal(sortie.outcome,'胜利');carry.army.rifle-=8;
let report=C.resolveAttack(carry,soft,sortie,now);
assert.equal(report.returned.rifle,8,'all surviving riflemen return without retraining');
assert.equal(carry.army.rifle,8);

let pending=C.createSave(now),paid=88;
pending.activeBattle={initialArmy:C.clone(pending.army),deploymentGoldPaid:paid};
pending.army.rifle=0;pending.resources.gold-=paid;
let memory={item:JSON.stringify(pending),getItem(){return this.item},setItem(k,v){this.item=v}};
let restored=C.loadSave(memory,now+10_000);
assert.equal(restored.army.rifle,8);
assert.equal(restored.resources.gold,C.createSave(now).resources.gold);
assert.equal(restored.activeBattle,undefined);
let legacy=C.createSave(now);
legacy.version=1;legacy.expandedIsland=false;
legacy.base.push({id:2,type:'sniper',x:-4.4,z:1.3,lvl:1});
let legacyStorage={item:JSON.stringify(legacy),getItem(){return this.item},setItem(k,v){this.item=v}};
let legacyMigrated=C.loadSave(legacyStorage,now);
assert.equal(legacyMigrated.version,5);assert.equal(legacyMigrated.expandedIsland,true);
assert.ok(Math.abs(legacyMigrated.base[1].x+5.94)<.02);
C.saveGame(legacyMigrated,legacyStorage);
assert.deepEqual(C.loadSave(legacyStorage,now).base,legacyMigrated.base,'migration happens once');
const shellTypes=['gold','wood','steel','store','sniper','mg','mortar','cannon'];
for(let version of [2,3]){let prior=C.createSave(now);prior.version=version;prior.resources={gold:850,wood:700,steel:480};prior.base=[prior.base[0],...shellTypes.map((type,i)=>({id:i+2,type,x:((i%3)-1)*4,z:i%2?3:-3,lvl:1}))];prior.army.rifle=5;prior.reports=[{kind:'进攻',outcome:'胜利',at:now,destruction:1}];prior.onboardSeen=true;prior.tutorialDone=true;prior.guideStep=4;prior.protectedUntil=now;prior.raidAt=now;
 let disk={item:JSON.stringify(prior),getItem(){return this.item},setItem(k,v){this.item=v}},clean=C.loadSave(disk,now+1000);
 assert.equal(clean.version,5);assert.deepEqual(clean.base.map(b=>b.type),['hq'],'old prebuilt starter must become HQ-only');assert.equal(clean.army.rifle,5);assert.equal(clean.reports.length,1);assert.ok(clean.resources.gold>=1500&&clean.resources.wood>=1250&&clean.resources.steel>=820);assert.ok(clean.protectedUntil>=now+24*3600000);assert.equal(clean.guideStep,0);assert.equal(clean.tutorialDone,false);assert.match(clean.migrationNotice,/已收回/);
 C.saveGame(clean,disk);assert.deepEqual(C.loadSave(disk,now+2000).base,clean.base,'v4 must not repeat the removal');
}
let built=C.createSave(now);built.version=3;built.base=[built.base[0],...shellTypes.map((type,i)=>({id:i+2,type,x:i,z:0,lvl:1})),{id:10,type:'sniper',x:8,z:-4,lvl:1}];let builtDisk={item:JSON.stringify(built),getItem(){return this.item}};assert.deepEqual(C.loadSave(builtDisk,now).base.map(b=>b.id),[1,10],'keep a tower added by the player');
let progressed=C.createSave(now);progressed.version=3;progressed.base=[progressed.base[0],...shellTypes.map((type,i)=>({id:i+2,type,x:i,z:0,lvl:1}))];progressed.base[0].lvl=2;let progressedDisk={item:JSON.stringify(progressed),getItem(){return this.item}};assert.equal(C.loadSave(progressedDisk,now).base.length,9,'do not wipe an upgraded HQ');
let oldReplay={...rep,version:1};delete oldReplay.spawnZ;
assert.equal(C.replayBattle(oldReplay).battle.spawnZ,5.5,'v1 replay coordinate');
let v2Replay={...rep,version:2},old=C.replayBattle(v2Replay).battle;
old.landBoat('rifle',8,0,0);
for(let i=0;i<42;i++)old.step();
assert.equal(old.units.length,8,'v2 replay original wave');
let previousBase=[{id:1,type:'hq',x:0,z:-6,lvl:1},{id:2,type:'mg',x:0,z:4.9,lvl:1}],previousCommands=[{t:0,kind:'land',type:'rifle',count:4,x:0,index:0,level:1}];
let previousRules=C.runCommands(new C.Battle(previousBase,73,'defense',null,1,C.MAP.spawnZ,3),previousCommands,135);
assert.ok(previousRules.units.some(u=>u.hp<u.maxHp),'legacy machine gun reaches troops');
let previousReplay={...previousRules.snapshot(),version:3},recreated=C.replayBattle(previousReplay);
assert.equal(recreated.battle.ruleset,3,'v3 replay keeps pre-inaccuracy machine gun');
C.runCommands(recreated.battle,recreated.commands,previousRules.tick);assert.deepEqual(recreated.battle.units.map(u=>u.hp),previousRules.units.map(u=>u.hp),'v3 replay retains earlier damage');
let v7Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,8.6,7),v8Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,8.6,8),v9Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,8.6,9),v10Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,8.6,10),v11Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,8.6,11),v12Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,12),v13Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,13),v14Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,14),v15Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,15),v16Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,16),v17Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,17,null,'night',.72),v18Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,18,null,'night',.72),v19Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,19,null,'night',.72),v20Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,20,null,'night',.72),v21Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,21,null,'night',.72),v22Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,22,null,'night',.72);
assert.equal(C.replayBattle(v7Heavy.snapshot()).battle.ruleset,7,'saved v7 reports retain their balance rules');
assert.equal(C.replayBattle(v8Heavy.snapshot()).battle.ruleset,8,'saved v8 reports retain the first heavy rebalance');
assert.equal(C.replayBattle(v9Heavy.snapshot()).battle.ruleset,9,'saved v9 reports retain the anti-steamroll heavy rules');assert.equal(C.replayBattle(v10Heavy.snapshot()).battle.ruleset,10,'v10 reports retain the revised gunboat rules');assert.equal(C.replayBattle(v11Heavy.snapshot()).battle.ruleset,11,'v11 reports retain movement, berthing and lock rules');assert.equal(C.replayBattle(v12Heavy.snapshot()).battle.ruleset,12,'v12 reports retain their original map and ranges');assert.equal(C.replayBattle(v13Heavy.snapshot()).battle.ruleset,13,'v13 reports retain the deeper-map and revised-range rules');assert.equal(C.replayBattle(v14Heavy.snapshot()).battle.ruleset,14,'v14 reports retain the first troop-damage reduction');assert.equal(C.replayBattle(v15Heavy.snapshot()).battle.ruleset,15,'v15 reports retain the 60-percent target balance');assert.equal(C.replayBattle(v16Heavy.snapshot()).battle.ruleset,16,'v16 reports retain nearest-building targeting and the 50-percent target balance');let replay17=C.replayBattle(v17Heavy.snapshot()).battle;assert.equal(replay17.ruleset,17);assert.equal(replay17.period,'night');assert.equal(replay17.periodProgress,.72,'v17 replay must lock its battle time and seamless-lighting position');let replay18=C.replayBattle(v18Heavy.snapshot()).battle;assert.equal(replay18.ruleset,18);assert.equal(replay18.period,'night');assert.equal(replay18.periodProgress,.72,'v18 replay must lock its range balance and battle lighting');let replay19=C.replayBattle(v19Heavy.snapshot()).battle;assert.equal(replay19.ruleset,19);assert.equal(replay19.period,'night');assert.equal(replay19.periodProgress,.72,'v19 replay must lock environmental visibility and battle lighting');let replay20=C.replayBattle(v20Heavy.snapshot()).battle;assert.equal(replay20.ruleset,20);assert.equal(replay20.period,'night');assert.equal(replay20.periodProgress,.72,'v20 replay must lock collision-aware pathing and battle lighting');let replay21=C.replayBattle(v21Heavy.snapshot()).battle;assert.equal(replay21.ruleset,21);assert.equal(replay21.period,'night');assert.equal(replay21.periodProgress,.72,'v21 replay must lock stronger defensive ranges and orderly landing departure');let replay22=C.replayBattle(v22Heavy.snapshot()).battle;assert.equal(replay22.ruleset,22);assert.equal(replay22.period,'night');assert.equal(replay22.periodProgress,.72,'v22 replay must lock the restored troop pressure');
let v23Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],4,'replay',null,1,C.MAP.spawnZ,23,null,'night',.72),replay23=C.replayBattle(v23Heavy.snapshot()).battle;assert.equal(replay23.ruleset,23);assert.equal(replay23.period,'night');assert.equal(replay23.periodProgress,.72,'v23 replay must lock formation pathing and one-day battle time');let v24Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],5,'replay',null,1,C.MAP.spawnZ,24,null,'night',.72),replay24=C.replayBattle(v24Heavy.snapshot()).battle;assert.equal(replay24.ruleset,24);assert.equal(replay24.period,'night');assert.equal(replay24.periodProgress,.72,'v24 replay must lock rear-escort medic guidance');let v25Heavy=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],6,'replay',null,1,C.MAP.spawnZ,25,null,'night',.72),replay25=C.replayBattle(v25Heavy.snapshot()).battle;assert.equal(replay25.ruleset,25);assert.equal(replay25.period,'night');assert.equal(replay25.periodProgress,.72,'v25 replay must lock turret traverse, acquisition and reload behavior');let oneDayBattle=new C.Battle([{id:1,type:'hq',x:0,z:-10,lvl:999}],458);oneDayBattle.deploy('medic',0,false,1,8);for(let i=0;i<30*131;i++)oneDayBattle.step();assert.equal(oneDayBattle.done,false,'current battles must not lose while living units remain just because 130 seconds passed');for(let i=oneDayBattle.tick;i<C.BATTLE_LIMIT_TICKS;i++)oneDayBattle.step();assert.equal(oneDayBattle.cause,'作战超过 24 小时','current battles must end only after one complete 12-minute game day');let timedReplay=new C.Battle([{id:1,type:'hq',x:0,z:-10,lvl:999}],459,'replay',null,1,C.MAP.spawnZ,22);timedReplay.deploy('medic',0,false,1,8);for(let i=0;i<30*130;i++)timedReplay.step();assert.equal(timedReplay.cause,'时间耗尽','v22 replay must retain its historical battle clock');
	v7Heavy.deploy('heavy',0,false,1,2.5);v8Heavy.deploy('heavy',0,false,1,2.5);v9Heavy.deploy('heavy',0,false,1,2.5);v10Heavy.deploy('heavy',0,false,1,2.5);v11Heavy.deploy('heavy',0,false,1,2.5);
	for(let i=0;i<19;i++){v7Heavy.step();v8Heavy.step();v9Heavy.step();v10Heavy.step();v11Heavy.step()}
assert.equal(v7Heavy.base[0].maxHp-v7Heavy.base[0].hp,44,'v7 heavy retains its two original shots');
assert.equal(v8Heavy.base[0].maxHp-v8Heavy.base[0].hp,20,'v8 heavy fires one reduced shot in the same period');
assert.equal(v9Heavy.base[0].maxHp-v9Heavy.base[0].hp,8,'v9 heavy is a durable frontliner instead of a one-boat damage carry');
assert.equal(v10Heavy.base[0].maxHp-v10Heavy.base[0].hp,8,'v10 keeps the anti-steamroll heavy balance');
let groundBase=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'gold',x:0,z:0,lvl:1}],oldGround=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,13),v14Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,14),v15Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,15),v17Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,17),v21Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,21),v26Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,26),v27Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,27),newGround=new C.Battle(groundBase,95);for(let b of [oldGround,v14Ground,v15Ground,v17Ground,v21Ground,v26Ground,v27Ground,newGround])b.deploy('rifle',0,false,1,4.1);for(let b of [oldGround,v14Ground,v15Ground,v17Ground,v21Ground,v26Ground,v27Ground,newGround])b.step();let oldGroundDamage=oldGround.base[1].maxHp-oldGround.base[1].hp,v14GroundDamage=v14Ground.base[1].maxHp-v14Ground.base[1].hp,v15GroundDamage=v15Ground.base[1].maxHp-v15Ground.base[1].hp,v17GroundDamage=v17Ground.base[1].maxHp-v17Ground.base[1].hp,v21GroundDamage=v21Ground.base[1].maxHp-v21Ground.base[1].hp,v26GroundDamage=v26Ground.base[1].maxHp-v26Ground.base[1].hp,v27GroundDamage=v27Ground.base[1].maxHp-v27Ground.base[1].hp,newGroundDamage=newGround.base[1].maxHp-newGround.base[1].hp;assert.ok(Math.abs(v14GroundDamage-oldGroundDamage*.8)<1e-9,'v14 must retain its 20 percent ground troop reduction');assert.ok(Math.abs(v15GroundDamage-oldGroundDamage*.4)<1e-9,'v15 must retain its 60 percent ground troop reduction');assert.ok(Math.abs(v17GroundDamage-oldGroundDamage*.34)<1e-9,'v17 must retain its shipped ground-troop damage scale');assert.ok(Math.abs(v21GroundDamage-oldGroundDamage*.4)<1e-9,'v21 replay must retain the 40 percent ground-troop scale');assert.ok(Math.abs(v26GroundDamage-oldGroundDamage*.52)<1e-9,'v26 replay must retain the 52 percent ground-troop scale');assert.ok(Math.abs(v27GroundDamage-oldGroundDamage*.35)<1e-9,'v27 replay must retain the 35 percent ground-troop scale');assert.equal(newGroundDamage,oldGroundDamage,'v28 troops must deal their full displayed damage');assert.equal(v27Ground.base[1].maxHp,oldGround.base[1].maxHp,'v27 replay must retain historical structure health');assert.equal(newGround.base[1].maxHp,Math.round(oldGround.base[1].maxHp*C.BATTLE_STRUCTURE_HP_SCALE),'v28 must move the balance into visible structure health');oldGround.fire(0,0,false);v27Ground.fire(0,0,false);newGround.fire(0,0,false);assert.equal(v27Ground.gunboatShells[0].damage,oldGround.gunboatShells[0].damage,'v27 replay must retain historical gunboat damage');assert.equal(newGround.gunboatShells[0].damage,C.gunboatDamage('fire',1),'v28 gunboat damage must rise with structure health');
let v18Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,18),v19Ground=new C.Battle(groundBase,95,'replay',null,1,C.MAP.spawnZ,19);for(let b of [v18Ground,v19Ground]){b.deploy('rifle',0,false,1,4.1);b.step();assert.ok(Math.abs((b.base[1].maxHp-b.base[1].hp)-oldGroundDamage*.305)<1e-9,`v${b.ruleset} replay must retain the 30.5 percent ground-troop scale`)}
let bypassBase=[{id:1,type:'hq',x:12,z:-10,lvl:1},{id:2,type:'gold',x:0,z:8.6,lvl:1},{id:3,type:'cannon',x:0,z:7.4,lvl:1}],oldBypass=new C.Battle(bypassBase,96,'replay',null,1,C.MAP.spawnZ,15),nearestBuilding=new C.Battle(bypassBase,96);oldBypass.deploy('rifle',0,false,1,14);nearestBuilding.deploy('rifle',0,false,1,14);oldBypass.step();nearestBuilding.step();assert.equal(oldBypass.units[0].targetId,3,'v15 replay must preserve the former defense-priority target');assert.equal(nearestBuilding.units[0].targetId,2,'current troops must attack the nearest building instead of walking past it toward a farther cannon');
let walk10=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],44,'replay',null,1,8.6,10),walk11=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],44,'replay',null,1,8.6,11);walk10.deploy('heavy',0,false,1,8.6);walk11.deploy('heavy',0,false,1,8.6);for(let i=0;i<20;i++){walk10.step();walk11.step()}assert.ok(walk11.units[0].walk<walk10.units[0].walk*.8,'v11 troops move slower than the previous ruleset');
let standardWalk=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],144,'replay',null,1,C.MAP.spawnZ,17,null,'standard'),morningWalk=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],144,'replay',null,1,C.MAP.spawnZ,17,null,'morning'),nightWalk=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],144,'replay',null,1,C.MAP.spawnZ,17,null,'night');for(let b of [standardWalk,morningWalk,nightWalk])b.deploy('rifle',0,false,1,8);for(let i=0;i<20;i++){standardWalk.step();morningWalk.step();nightWalk.step()}assert.ok(morningWalk.units[0].walk>standardWalk.units[0].walk*1.07,'morning must speed up troops');assert.ok(nightWalk.units[0].walk<standardWalk.units[0].walk*.95,'night must slow troops');
let weatherBase=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'sniper',x:0,z:0,lvl:1}],standardRange=new C.Battle(weatherBase,145,'replay',null,1,C.MAP.spawnZ,17,null,'standard'),noonRange=new C.Battle(weatherBase,145,'replay',null,1,C.MAP.spawnZ,17,null,'noon'),nightRange=new C.Battle(weatherBase,145,'replay',null,1,C.MAP.spawnZ,17,null,'night');for(let b of [standardRange,noonRange,nightRange])b.deploy('rifle',0,false,1,7.1);standardRange.step();noonRange.step();nightRange.step();assert.equal(standardRange.base[1].targetId,undefined);assert.equal(noonRange.base[1].targetId,1,'noon range bonus must acquire a target beyond base range');assert.equal(nightRange.base[1].targetId,undefined,'night visibility must not retain the noon range');
let windyBase=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],calmRockets=new C.Battle(windyBase,146,'replay',null,1,C.MAP.spawnZ,17,null,'standard'),windyRockets=new C.Battle(windyBase,146,'replay',null,1,C.MAP.spawnZ,17,null,'afternoon');for(let b of [calmRockets,windyRockets]){b.deploy('rifle',8,false,1,0);b.step()}let shellError=b=>b.projectiles.reduce((n,p)=>n+C.distance(p,{x:8,z:0}),0)/b.projectiles.length;assert.ok(Math.abs(shellError(windyRockets)/shellError(calmRockets)-1.25)<1e-9,'afternoon wind must increase explosive scatter by 25 percent');
let modernStandardWalk=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],244,'replay',null,1,C.MAP.spawnZ,19,null,'standard'),modernMorningWalk=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],244,'replay',null,1,C.MAP.spawnZ,19,null,'morning');for(let b of [modernStandardWalk,modernMorningWalk])b.deploy('rifle',0,false,1,8);for(let i=0;i<20;i++){modernStandardWalk.step();modernMorningWalk.step()}assert.ok(Math.abs(modernMorningWalk.units[0].walk/modernStandardWalk.units[0].walk-.9)<1e-9,'v19 morning sleepiness slows movement by ten percent instead of adding a buff');
let sleepyBase=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'sniper',x:0,z:0,lvl:1}],awakeTower=new C.Battle(sleepyBase,245,'replay',null,1,C.MAP.spawnZ,19,null,'standard'),sleepyTower=new C.Battle(sleepyBase,245,'replay',null,1,C.MAP.spawnZ,19,null,'morning');for(let b of [awakeTower,sleepyTower]){b.deploy('rifle',0,false,1,4);b.step()}assert.ok(Math.abs((sleepyTower.units[0].maxHp-sleepyTower.units[0].hp)/(awakeTower.units[0].maxHp-awakeTower.units[0].hp)-.9)<1e-9,'morning towers deal ten percent less damage');assert.ok(sleepyTower.base[1].cool>awakeTower.base[1].cool,'morning towers also take longer between shots');
let visibleBase=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'sniper',x:0,z:0,lvl:1}],normalSight=new C.Battle(visibleBase,246,'replay',null,1,C.MAP.spawnZ,19,null,'standard'),highSunSight=new C.Battle(visibleBase,246,'replay',null,1,C.MAP.spawnZ,19,null,'noon'),darkSight=new C.Battle(visibleBase,246,'replay',null,1,C.MAP.spawnZ,19,null,'night');for(let b of [normalSight,highSunSight,darkSight]){b.deploy('rifle',0,false,1,7.1);b.step()}assert.equal(normalSight.base[1].targetId,undefined);assert.equal(highSunSight.base[1].targetId,1,'noon visibility must extend defensive acquisition');assert.equal(darkSight.base[1].targetId,undefined,'night visibility must shorten defensive acquisition');
let rangeTarget=[{id:1,type:'hq',x:0,z:0,lvl:1}],normalTroopSight=new C.Battle(rangeTarget,247,'replay',null,1,C.MAP.spawnZ,19,null,'standard'),highSunTroopSight=new C.Battle(rangeTarget,247,'replay',null,1,C.MAP.spawnZ,19,null,'noon'),darkTroopSight=new C.Battle(rangeTarget,247,'replay',null,1,C.MAP.spawnZ,19,null,'night');for(let b of [normalTroopSight,highSunTroopSight,darkTroopSight]){b.deploy('rifle',0,false,1,5.3);b.step();b.step()}assert.equal(normalTroopSight.base[0].hp,normalTroopSight.base[0].maxHp);assert.ok(highSunTroopSight.base[0].hp<highSunTroopSight.base[0].maxHp,'noon visibility must extend troop attack distance too');assert.equal(darkTroopSight.base[0].hp,darkTroopSight.base[0].maxHp,'night must not retain the noon troop visibility');
let afternoonUnitMisses=0,afternoonTowerMisses=0;for(let seed=1;seed<=400;seed++){let unitWeather=new C.Battle(rangeTarget,seed,'replay',null,1,C.MAP.spawnZ,19,null,'afternoon');unitWeather.deploy('rifle',0,false,1,4.5);unitWeather.step();if(unitWeather.events.some(e=>e.kind==='shot'&&e.miss))afternoonUnitMisses++;let towerWeather=new C.Battle(sleepyBase,seed,'replay',null,1,C.MAP.spawnZ,19,null,'afternoon');towerWeather.deploy('rifle',0,false,1,4);towerWeather.step();if(towerWeather.units[0].hp===towerWeather.units[0].maxHp)afternoonTowerMisses++}assert.ok(afternoonUnitMisses>=48&&afternoonUnitMisses<=80,'afternoon glare must produce a deterministic roughly sixteen-percent troop miss rate');assert.ok(afternoonTowerMisses>=48&&afternoonTowerMisses<=80,'afternoon glare must affect direct-fire defenses too');
let calmModernRockets=new C.Battle(windyBase,248,'replay',null,1,C.MAP.spawnZ,19,null,'standard'),duskModernRockets=new C.Battle(windyBase,248,'replay',null,1,C.MAP.spawnZ,19,null,'afternoon');for(let b of [calmModernRockets,duskModernRockets]){b.deploy('rifle',8,false,1,0);b.step()}assert.ok(Math.abs(shellError(duskModernRockets)/shellError(calmModernRockets)-1.18)<1e-9,'v19 dusk must widen explosive scatter by eighteen percent');
let quietLanding=new C.Battle([{id:1,type:'hq',x:20,z:20,lvl:1}],249,'attack',null,1,C.MAP.spawnZ,19,null,'night');quietLanding.landBoat('rifle',1,0,0,1,false,10.2);for(let i=0;i<80;i++)quietLanding.step();assert.equal(quietLanding.engaged,false,'landing and walking without an encounter must keep the stealth music layer');let warshipContact=new C.Battle(rangeTarget,250,'attack',null,1,C.MAP.spawnZ,19,null,'night');warshipContact.useSkill('flare',0,0,null,false);assert.equal(warshipContact.engaged,true,'firing a warship weapon immediately counts as contact');for(let i=0;i<181;i++)warshipContact.step();assert.equal(warshipContact.engaged,false,'six seconds without any shot or blast must return to the stealth layer');let medicDrop=new C.Battle(rangeTarget,251,'attack',null,1,C.MAP.spawnZ,19,null,'night');medicDrop.useSkill('medkit',0,0,null,false);assert.equal(medicDrop.engaged,false,'a medical drop alone is not a firefight');
assert.deepEqual([C.BUILD.sniper.range,C.BUILD.mortar.range],[8.16,8.16],'sniper tower and mortar keep equal twenty-percent-buffed ranges');assert.deepEqual([C.BUILD.mg.range,C.BUILD.cannon.range],[6.84,6.84],'machine gun and cannon keep equal twenty-percent-buffed ranges');assert.deepEqual([C.UNIT.heavy.range,C.UNIT.rifle.range,C.UNIT.rocket.range,C.UNIT.tank.range],[2.97,4.2,5.2,6.4],'troop ranges must form the intended heavy, rifle, rocket and tank formation');assert.ok(Math.abs(C.UNIT.heavy.range-3.3*.9)<1e-9,'heavy gunner range must be reduced by exactly 10 percent');assert.ok(C.UNIT.heavy.range<C.UNIT.rifle.range&&C.UNIT.rifle.range<C.UNIT.rocket.range&&C.UNIT.rocket.range<C.UNIT.tank.range,'troop formation ranges are not strictly front-to-back');assert.ok(C.UNIT.tank.range<C.BUILD.cannon.range&&C.UNIT.tank.range<C.BUILD.sniper.range,'front-line defenses must now acquire a tank before its firing stop');assert.equal(C.BUILD.rocket.range,14.4);assert.equal(C.BUILD.rocket.min,5.28,'rocket launcher blind spot must increase by exactly twenty percent');
for(let [type,z] of [['sniper',7.5],['mg',6.2],['mortar',7.5],['cannon',6.2]]){let base=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type,x:0,z:0,lvl:1}],v20=new C.Battle(base,190,'replay',null,1,C.MAP.spawnZ,20),v21=new C.Battle(base,190,'replay',null,1,C.MAP.spawnZ,21);v20.deploy('rifle',0,false,1,z);v21.deploy('rifle',0,false,1,z);v20.step();v21.step();assert.equal(v20.base[1].targetId,undefined,`v20 ${type} must preserve its old outer range`);assert.equal(v21.base[1].targetId,1,`v21 ${type} did not acquire inside its twenty-percent extension`)}let v20MortarBlind=new C.Battle([{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'mortar',x:0,z:0,lvl:1}],191,'replay',null,1,C.MAP.spawnZ,20),v21MortarBlind=new C.Battle([{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'mortar',x:0,z:0,lvl:1}],191,'replay',null,1,C.MAP.spawnZ,21);v20MortarBlind.deploy('rifle',0,false,1,1.85);v21MortarBlind.deploy('rifle',0,false,1,1.85);v20MortarBlind.step();v21MortarBlind.step();assert.equal(v20MortarBlind.base[1].targetId,1,'v20 mortar must preserve the 1.7 blind zone');assert.equal(v21MortarBlind.base[1].targetId,undefined,'v21 mortar must enforce the twenty-percent-larger blind zone');

let oldRifleRange=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],181,'replay',null,1,C.MAP.spawnZ,17),newRifleRange=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],181);oldRifleRange.deploy('rifle',0,false,1,4.85);newRifleRange.deploy('rifle',0,false,1,4.85);oldRifleRange.step();newRifleRange.step();assert.equal(oldRifleRange.base[0].hp,oldRifleRange.base[0].maxHp,'v17 rifle replay must retain its shorter range');assert.ok(newRifleRange.base[0].hp<newRifleRange.base[0].maxHp,'v18 rifle must use its increased range');
let oldHeavyRange=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],182,'replay',null,1,C.MAP.spawnZ,17),newHeavyRange=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],182);oldHeavyRange.deploy('heavy',0,false,1,3.9);newHeavyRange.deploy('heavy',0,false,1,3.9);oldHeavyRange.step();newHeavyRange.step();assert.ok(oldHeavyRange.base[0].hp<oldHeavyRange.base[0].maxHp,'v17 heavy replay must retain its 3.3 range');assert.equal(newHeavyRange.base[0].hp,newHeavyRange.base[0].maxHp,'v18 heavy must move before firing at the old range');
let rocketBlindBase=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type:'rocket',x:0,z:0,lvl:1}],oldRocketBlind=new C.Battle(rocketBlindBase,183,'replay',null,1,C.MAP.spawnZ,17),newRocketBlind=new C.Battle(rocketBlindBase,183);oldRocketBlind.deploy('rifle',0,false,1,4);newRocketBlind.deploy('rifle',0,false,1,4);oldRocketBlind.step();newRocketBlind.step();assert.equal(oldRocketBlind.base[1].targetId,1,'v17 rocket replay must retain its smaller blind spot');assert.equal(newRocketBlind.base[1].targetId,undefined,'v18 rocket launcher must not lock inside the enlarged blind spot');
for(let [type,z] of [['sniper',6.2],['mg',5.45],['cannon',5.25]]){let base=[{id:1,type:'hq',x:20,z:20,lvl:1},{id:2,type,x:0,z:0,lvl:1}],oldRange=new C.Battle(base,91,'replay',null,1,C.MAP.spawnZ,12),newRange=new C.Battle(base,91);oldRange.deploy('rifle',0,false,1,z);newRange.deploy('rifle',0,false,1,z);oldRange.step();newRange.step();assert.equal(oldRange.base[1].targetId,undefined,`v12 ${type} range changed`);assert.equal(newRange.base[1].targetId,1,`v13 ${type} did not acquire at its new range`)}
let oldTank=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],92,'replay',null,1,C.MAP.spawnZ,12),newTank=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],92);oldTank.deploy('tank',0,false,1,6.2);newTank.deploy('tank',0,false,1,6.2);oldTank.step();newTank.step();assert.equal(oldTank.base[0].hp,oldTank.base[0].maxHp,'v12 tank range changed');assert.ok(newTank.base[0].hp<newTank.base[0].maxHp,'current tank did not fire from its increased range');let oldMapBattle=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],93,'replay',null,1,C.MAP.spawnZ,12),newMapBattle=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],93);assert.equal(oldMapBattle.landBoat('rifle',1,12.8,0),false,'v12 replay accepted a v13-only berth');assert.equal(newMapBattle.landBoat('rifle',1,12.8,0),true,'current map did not retain the wider beach');
let medicLine=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],55);medicLine.deploy('rifle',0,false,1,6);medicLine.deploy('medic',0,false,1,6);for(let i=0;i<40;i++)medicLine.step();let fighter=medicLine.units.find(u=>u.type==='rifle'),doctor=medicLine.units.find(u=>u.type==='medic');assert.ok(doctor.z>fighter.z+1.4&&C.distance(doctor,fighter)<=C.UNIT.medic.range+.5,'doctor follows the formation from a medium-distance rear position');
let escortBase=[{id:1,type:'hq',x:10,z:-8,lvl:10},{id:2,type:'sniper',x:0,z:0,lvl:1}],oldEscort=new C.Battle(escortBase,777,'replay',null,1,C.MAP.spawnZ,23),flareEscort=new C.Battle(escortBase,777);for(let b of [oldEscort,flareEscort]){b.deploy('tank',0,false,1,7.3);b.deploy('medic',0,false,1,9.6);b.flareAt(0,0,2,false);for(let i=0;i<150;i++)b.step()}let oldEscortTank=oldEscort.units[0],oldEscortMedic=oldEscort.units[1],escortTank=flareEscort.units[0],escortMedic=flareEscort.units[1];assert.ok(oldEscortMedic.z<oldEscortTank.z-2,'v23 replay must preserve its historical direct-flare medic movement');assert.ok(flareEscort.base[1].hp<flareEscort.base[1].maxHp,'the guided tank must fire on the marked building');assert.ok(escortMedic.z>escortTank.z+2&&C.distance(escortMedic,escortTank)<C.UNIT.medic.range+.5,'a medic must follow behind a flare-guided tank instead of walking into the marked building');assert.equal(escortMedic.hp,escortMedic.maxHp,'the rear escort medic should not expose itself to the marked defense');assert.ok(escortTank.hp>oldEscortTank.hp+150,'the rear escort medic must remain close enough to keep healing the firing tank');
let oneHeavyWins=0;for(let seed=1;seed<=100;seed++){let island=null;for(let i=0;i<48&&!island;i++)island=C.generateEnemy(seed+i*43,1);let result=C.runCommands(new C.Battle(island.base,island.seed),[{t:1,kind:'land',type:'heavy',count:4,index:0,level:1,x:0}]);oneHeavyWins+=result.outcome==='胜利'}assert.ok(oneHeavyWins<30,'one heavy boat still steamrolls too many complete HQ1 bases: '+oneHeavyWins);

let away=C.createSave(now);C.settle(away,now+181*86400000,true);
assert.ok(away.reports.length<=1);
let hit=0;
for(let i=0;i<100;i++){
 let save=C.createSave(now);save.seed=i;save.raidAt=now;save.protectedUntil=now;
 C.settle(save,now+2*86400000,true);hit+=save.reports.length;
 if(save.reports.length){assert.equal(save.protectedUntil,now+2*86400000+6*3600000);save.raidAt=now;C.settle(save,now+2*86400000+3600000,true);assert.equal(save.reports.length,1)}
 let previous=save.reports.length;C.settle(save,now+2*86400000+3600000+2000,true);assert.equal(save.reports.length,previous)
}
assert.ok(hit>15&&hit<55,'offline raid probability '+hit+'/100');
let clock=C.createSave(now),day1=new Date(2026,8,25,10).getTime(),day2=new Date(2026,8,26,10).getTime();
assert.equal(C.recordOnline(clock,8*3600000-1,day1),false);
assert.equal(C.recordOnline(clock,2,day1),true);
assert.equal(C.recordOnline(clock,1000,day1),false);
assert.equal(C.recordOnline(clock,8*3600000,day1),true);
assert.equal(C.recordOnline(clock,8*3600000,day1),false);
assert.equal(clock.onlineClock.gates,2);
assert.equal(C.recordOnline(clock,1000,day2),false);
assert.equal(clock.onlineClock.gates,0);
assert.equal(C.recordOnline(clock,8*3600000,day2),true);

let ranged=[];for(let type of ['rifle','heavy']){let stage=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],52);stage.deploy(type,0,false,1,C.MAP.spawnZ);for(let t=0;t<320&&stage.base[0].hp===stage.base[0].maxHp;t++)stage.step();assert.ok(stage.base[0].hp<stage.base[0].maxHp,`${type} should fire before touching HQ`);ranged.push(C.distance(stage.units[0],stage.base[0]))}
assert.ok(ranged[0]>ranged[1]+1&&ranged[0]<ranged[1]+1.45,'heavy infantry should hold the front while riflemen fire from the second line');
let beach=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],9);assert.equal(beach.landBoat('rifle',19,0,0),false,'one boat cannot spawn more than the largest craft holds');assert.equal(beach.landBoat('rifle',8,Number.NaN,0),false);assert.equal(beach.landBoat('rifle',8,0,0),true);for(let t=0;t<72;t++)beach.step();assert.ok(beach.units.length&&beach.units.every(u=>u.z>=C.MAP.beachZ),'first wave must leave the boat at the beach');
let legacyBeach=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],9,'replay',null,1,5.5,5);assert.equal(legacyBeach.landBoat('rifle',8,0,0),true,'previous replay beach stays compatible');
let escalation=new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1}],5,'attack',null,5);assert.equal(escalation.maxEnergy,27);assert.deepEqual(['fire','barrage','shock'].map(k=>escalation.skillCost(k)),[4,7,5]);
assert.equal(escalation.fire(0,0),true);assert.equal(escalation.skillCost('fire'),6);assert.equal(escalation.fire(0,0),true);assert.equal(escalation.skillCost('fire'),8);assert.equal(escalation.fire(0,0),true);assert.equal(escalation.skillCost('fire'),10);assert.equal(escalation.fire(0,0),false,'next shot must be unaffordable');
let wide=new C.Battle([{id:1,type:'hq',x:0,z:-6,lvl:1}],37,'attack',null,5),priorWide=new C.Battle([{id:1,type:'hq',x:0,z:-6,lvl:1}],37,'replay',null,5,C.MAP.spawnZ,5),v9Gunboat=new C.Battle([{id:1,type:'hq',x:0,z:-6,lvl:1}],37,'replay',null,5,C.MAP.spawnZ,9);assert.equal(wide.useSkill('barrage',0,-6),true);assert.equal(priorWide.useSkill('barrage',0,-6),true);v9Gunboat.fire(0,-6);v9Gunboat.useSkill('barrage',0,-6);let avgOuter=b=>b.gunboatShells.slice(3).reduce((total,s)=>total+C.distance(s,{x:0,z:-6}),0)/7;assert.ok(avgOuter(wide)>avgOuter(priorWide)*1.48,'outer rockets still scatter widely at long range');assert.equal(wide.gunboatShells[0].damage,C.gunboatDamage('barrage',1));assert.equal(v9Gunboat.gunboatShells[0].radius,1.25);assert.equal(v9Gunboat.gunboatShells[1].damage,65,'v9 gunboat replay retains previous artillery radius and rocket damage');assert.equal(priorWide.gunboatShells[0].damage,43);assert.equal(priorWide.gunboatShells[0].land,14);for(let i=0;i<90;i++)wide.step();assert.ok(wide.base[0].maxHp-wide.base[0].hp>=2*C.gunboatDamage('barrage',1),'a stabilized long-range rocket volley should still land some splash hits after all staggered rockets arrive');
assert.equal(priorWide.skillCost('barrage'),10,'v5 replay keeps original fixed rocket cost');assert.equal(priorWide.maxEnergy,54,'v5 replay keeps original energy');assert.equal(new C.Battle([{id:1,type:'hq',x:0,z:0,lvl:1},{id:2,type:'sniper',x:4,z:0,lvl:1}],5,'replay',null,1,C.MAP.spawnZ,5).base[1].maxHp,240,'old replay keeps original defensive HP');
let interrupted=C.createSave(now);interrupted.resources.gold-=C.SORTIE_FEE;interrupted.activeBattle={initialArmy:C.clone(interrupted.army),entryGoldPaid:C.SORTIE_FEE,deploymentGoldPaid:0};assert.equal(C.loadSave({getItem:()=>JSON.stringify(interrupted)},now).resources.gold,1500,'interrupted outing returns the entry fee');
assert.ok(C.generateEnemy(4,1).reward.gold>500,'level-one victory should pay more than 300 gold');
console.log('24,000 layouts, beach, HQ quotas, economy, ranges, energy escalation, replay versions, offline raids: OK');
