import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import * as C from '../src/core.js';import {droneEra,droneRotorSpec,makeRotorGuard,Renderer} from '../src/render.js';
function fixture(gap=6,rule=C.CURRENT_RULESET){let b=new C.Battle([{id:1,type:'hq',lvl:10,x:14,z:-12},{id:2,type:'drone',lvl:1,x:0,z:0}],77,'attack',null,1,C.MAP.spawnZ,rule);b.deploy('heavy',0,true,1,gap);b.units[0].hp=b.units[0].maxHp=10000;b.units[0].cool=Infinity;b.advanceUnit=()=>0;b.resolveUnitCollisions=()=>{};b.base.forEach(v=>v.hp=v.maxHp=100000);return b}
const old=fixture(6,29),trace=[];for(let i=0;i<900;i++){old.step();trace.push(JSON.stringify({tick:old.tick,drone:old.base[1].drone,cool:old.base[1].cool,hp:old.units[0].hp,projectiles:old.projectiles,events:old.events}))}assert.equal(createHash('sha256').update(trace.join('\n')).digest('hex'),'ed3c1b764d725a766279e98757a8669948fb71af2821a8c8454f3483ac0cf3f3');
const battle=fixture(),pad=battle.base[1],phases=new Map(),samples={},drops=[],returns=[];let previous,ended=false;
for(let i=0;i<1600;i++){battle.step();let d=pad.drone;if(d){phases.set(d.phase,(phases.get(d.phase)||0)+1);(samples[d.phase]??=[]).push({...d});if(previous){assert.ok(Math.abs(d.y-previous.y)<.11);assert.ok(Math.abs(d.rpm-previous.rpm)<.06);assert.ok(Math.abs(C.shortestAngle(d.heading,previous.heading))<.081)}if(['spool','takeoff','hover'].includes(d.phase)){assert.equal(d.x,0);assert.equal(d.z,0)}previous={...d}}for(let event of battle.events.filter(e=>e.at===battle.tick)){if(event.kind==='droneDrop')drops.push(event.at);if(event.kind==='droneReturn'){returns.push(event.at);assert.equal(pad.cool,90);ended=true}}if(ended)break}
assert.deepEqual([...phases.keys()],['spool','takeoff','hover','outbound','drop','return','landing','spindown']);assert.equal(drops.length,1);assert.equal(returns.length,1);assert.ok(phases.get('takeoff')>=47&&phases.get('landing')>=47&&phases.get('hover')>=26);for(let phase of ['takeoff','landing']){const s=samples[phase];assert.ok(Math.abs(s[1].y-s[0].y)<.002);assert.ok(Math.abs(s.at(-1).y-s.at(-2).y)<.01)}
let canceled=fixture();while(canceled.base[1].drone?.phase!=='hover')canceled.step();canceled.units[0].hp=0;let canceledDrops=0;for(let i=0;i<800&&canceled.base[1].drone;i++){canceled.step();canceledDrops+=canceled.events.filter(e=>e.kind==='droneDrop'&&e.at===canceled.tick).length}assert.equal(canceledDrops,0);assert.equal(canceled.base[1].drone,null);
assert.deepEqual(Array.from({length:10},(_,i)=>droneEra(i+1)),['rough','rough','industrial','industrial','industrial','modern','modern','modern','future','future']);const mesh=makeRotorGuard();for(let i=0;i<mesh.length;i+=6){assert.ok(Math.hypot(mesh[i],mesh[i+2])>=.41999);assert.ok(Math.abs(Math.hypot(mesh[i+3],mesh[i+4],mesh[i+5])-1)<1e-9)}for(let level=6;level<=10;level++){let s=droneRotorSpec(level);assert.ok(s.guardDiameter*s.innerRatio>s.bladeDiameter+.07);assert.ok(s.x*2>s.guardDiameter+.2);assert.ok(s.z*2>s.guardDiameter+.2)}
const ok={},gl=new Proxy({createShader:()=>ok,createProgram:()=>ok,createVertexArray:()=>ok,createBuffer:()=>ok,getShaderParameter:()=>true,getProgramParameter:()=>true,getUniformLocation:()=>0},{get:(t,k)=>k in t?t[k]:typeof k==='string'&&k.toUpperCase()===k?1:()=>{}});const view=new Renderer({getContext:()=>gl,clientWidth:1100,clientHeight:820});for(let level=1;level<=10;level++){let guards=0,draw=view.draw;view.draw=function(kind,x,y,...args){if(kind==='rotorGuard'&&Math.abs(y-1.13)<1e-7)guards++;return draw.call(this,kind,x,y,...args)};view.building({id:1,type:'drone',lvl:level,x:0,z:0});view.draw=draw;assert.equal(guards,level>=6?4:0)}
const replay=C.replayBattle(battle.snapshot());assert.equal(battle.snapshot().version,30);assert.equal(replay.battle.ruleset,30);assert.equal(C.replayBattle(old.snapshot()).battle.ruleset,29);console.log('0.6.8.5: historical drone trace unchanged; eased rotor/height/heading, hover, one grenade, canceled sortie, four eras, hollow guard/blade clearance and replay version OK');
