import assert from 'node:assert/strict';
import * as C from '../src/core.js';
import {Renderer} from '../src/render.js';
const now=1_900_000_000_000,caps=[3,3,4,4,5,6,6,7,7,8];
for(let level=1;level<=10;level++){let s=C.createSave(now);s.base[0].lvl=level;assert.equal(C.maxBoats(s),caps[level-1]);assert.equal(C.buildingLimit(s,'drone'),level<7?0:1);assert.equal(C.npcBuildCounts(level).drone||0,level<7?0:1)}
let fleet=C.createSave(now);fleet.base[0].lvl=10;let clock=now;
while(fleet.craft.count<8){fleet.resources={gold:100000,wood:100000,steel:100000};let expected=fleet.craft.count+1;assert.match(C.addCraft(fleet,clock),/建造中/);assert.equal(fleet.craft.count,expected-1);clock=fleet.upgrades.find(u=>u.craftBuild).end;C.settle(fleet,clock,false);assert.equal(fleet.craft.count,expected);assert.equal(fleet.craft.levels.at(-1),1);assert.equal(fleet.craft.loadouts.at(-1),'rifle')}
let before={...fleet.resources};assert.match(C.addCraft(fleet,clock),/8 艘上限/);assert.deepEqual(fleet.resources,before);fleet.resources.gold=100000;let refill=C.refillBoat(fleet,7,clock);assert.match(refill,/8 号艇.*补.*人/);clock=fleet.craft.refills.find(r=>r.index===7).end;C.settle(fleet,clock,false);assert.equal(C.boatManifest(fleet)[7].count,8);let restored=C.loadSave({getItem:()=>JSON.stringify(fleet)},clock);assert.equal(restored.craft.count,8);assert.equal(C.boatManifest(restored)[7].count,8);
let landing=new C.Battle([{id:1,type:'hq',lvl:10,x:0,z:-12}],91);for(let index=0;index<8;index++)assert.equal(landing.landBoat('rifle',1,0,index,1,true,12,8),true);assert.equal(new Set(landing.usedBerths).size,8);for(let i=0;i<8;i++)for(let j=i+1;j<8;j++)assert.ok(Math.abs(landing.usedBerths[i]-landing.usedBerths[j])>=C.LANDING_BOAT_SPACING-.01);for(let i=0;i<150;i++)landing.step();assert.equal(landing.deployed,8);
const ok={},gl=new Proxy({createShader:()=>ok,createProgram:()=>ok,createVertexArray:()=>ok,createBuffer:()=>ok,getShaderParameter:()=>true,getProgramParameter:()=>true,getUniformLocation:()=>0},{get:(t,k)=>k in t?t[k]:typeof k==='string'&&k.toUpperCase()===k?1:()=>{}});globalThis.devicePixelRatio=1;const view=new Renderer({getContext:()=>gl,clientWidth:1100,clientHeight:820,getBoundingClientRect:()=>({left:0,top:0,width:1100,height:820})});let ships=0,ship=view.ship;view.ship=function(...args){if(!args[2])ships++;return ship.apply(this,args)};view.render(fleet.base,null,-1,0,8,C.boatManifest(fleet));assert.equal(ships,8,'all eight craft must actually render');assert.equal(new Set(Array.from({length:8},(_,i)=>JSON.stringify(view.homeBoatPosition(i,8)))).size,8);
let pad=C.createSave(now);pad.base[0].lvl=7;pad.resources={gold:100000,wood:100000,steel:100000};assert.match(C.buildAt(pad,'drone',8,-10,now),/开工/);before={...pad.resources};assert.equal(C.buildingLimit(pad,'drone'),1);assert.ok(!C.buildAt(pad,'drone',-8,-10,now).includes('开工'));assert.deepEqual(pad.resources,before);pad.base[0].lvl=10;assert.equal(C.buildingLimit(pad,'drone'),1);
function fixture(gap=6,seed=77){let b=new C.Battle([{id:1,type:'hq',lvl:10,x:14,z:-12},{id:2,type:'drone',lvl:1,x:0,z:0}],seed);b.deploy('heavy',0,true,1,gap);b.units[0].hp=b.units[0].maxHp=10000;b.units[0].cool=Infinity;b.advanceUnit=()=>0;b.resolveUnitCollisions=()=>{};b.base.forEach(v=>v.hp=v.maxHp=100000);return b}
let counts=new Map([[1,0],[2,0],[3,0]]);for(let seed=1;seed<=4096;seed++){let b=fixture(3,seed);b.deploy('medic',0,false,1,21);b.deploy('rocket',-12,false,1,8);b.deploy('rifle',0,false,1,27);b.tick=1;let target=b.pickDroneTarget(b.base[1],26);assert.notEqual(target.id,4);counts.set(target.id,counts.get(target.id)+1)}assert.ok([...counts.values()].every(n=>n>1100&&n<1600),'front/rear targets must receive comparable uniform probabilities');
function cycle(gap){let b=fixture(gap),pad=b.base[1],launches=[],drops=[],returns=[],lands=[],healthAtDrop;for(let n=0;n<1200&&launches.length<2;n++){let hp=b.units[0].hp;b.step();for(let e of b.events.filter(e=>e.at===b.tick)){if(e.kind==='droneLaunch')launches.push(e.at);if(e.kind==='droneDrop'){drops.push(e.at);healthAtDrop=b.units[0].hp;assert.equal(healthAtDrop,hp,'drop cannot apply damage before the grenade lands')}if(e.kind==='droneReturn')returns.push(e.at);if(e.kind==='blast'&&e.weapon==='grenade'){lands.push(e.at);assert.equal(hp-b.units[0].hp,72,'grenade damage must resolve exactly once')}}if(pad.drone)assert.ok(Number.isFinite(pad.drone.x+pad.drone.y+pad.drone.z));}assert.equal(launches.length,2);assert.equal(drops.length,1,'one grenade per sortie');assert.equal(lands.length,1);assert.equal(returns.length,1);assert.ok(launches[0]<drops[0]&&drops[0]<lands[0]&&lands[0]<returns[0]);assert.ok(launches[1]-returns[0]>=90,'reload begins only after landing');return {b,interval:launches[1]-launches[0]}}
let near=cycle(4),far=cycle(22);assert.ok(far.interval>near.interval+100,'long flight distance must lower sortie frequency');
let area=fixture(6);area.deploy('heavy',1.5,false,1,6);area.units[1].hp=area.units[1].maxHp=10000;area.units[1].cool=Infinity;while(!area.events.some(e=>e.weapon==='grenade'&&e.kind==='blast'))area.step();assert.equal(area.units[0].hp,9928);assert.equal(area.units[1].hp,9928,'grenade must damage neighboring enemies');
let retarget=fixture(18);retarget.deploy('heavy',5,false,1,12);retarget.units[1].cool=Infinity;retarget.step();let old=retarget.base[1].drone.targetId;retarget.units.find(u=>u.id===old).hp=0;for(let i=0;i<30;i++)retarget.step();assert.notEqual(retarget.base[1].drone.targetId,old);assert.ok(Math.hypot(retarget.base[1].drone.x,retarget.base[1].drone.z)<8,'retargeting must continue flight without teleporting');
let live=new C.Battle([{id:1,type:'hq',lvl:3,x:0,z:-12},{id:2,type:'drone',lvl:3,x:0,z:-3}],811);live.deploy('tank',-3,true,8);live.deploy('tank',3,true,8);for(let i=0;i<6000&&!live.done;i++)live.step();assert.ok(live.done);assert.equal(live.snapshot().version,C.CURRENT_RULESET);let replay=C.replayBattle(live.snapshot()),index=0;while(replay.battle.tick<live.tick){while(index<replay.commands.length&&replay.commands[index].t<=replay.battle.tick){let cmd=replay.commands[index++];replay.battle.deploy(cmd.type,cmd.x,false,cmd.level)}replay.battle.step()}assert.equal(replay.battle.ruleset,C.CURRENT_RULESET);assert.deepEqual(replay.battle.stats,live.stats,'drone target rolls, travel and grenade damage must replay exactly');
for(let level=1;level<=10;level++)view.render([{id:1,type:'drone',lvl:level,x:0,z:0}],null,-1,level,0,[]);console.log('0.6.8.4: eight-craft build/refill/save/render/deploy, singleton drone, uniform targeting, single grenade, travel-based cycle, area damage and replay OK',Object.fromEntries(counts));
